export const dummy = {
	"field_types": {
	  "meta": "long",
	  "repos": "list",
	  "count": "long",
	  "사용자종류": "string",
	  "login": "string",
	  "type": "list",
	  "_time": "string"
	},
	"result": [
	  {
		"meta": 1,
		"repos": [
		  "09superm/python_project_2019",
		  "09superm/supermin.github.io",
		  "09superm/yesyes",
		  "metatron-app/metatron-discovery",
		  "s745812369s/python_project-2019-01",
		  "ysunmi0427/awesome-data-analysis-slides"
		],
		"count": 54,
		"사용자종류": null,
		"login": "09superm",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-06-10 02:12:17.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "0ct23rd",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-26 07:18:02.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "0hJiHye/0hJiHye.github.io",
		  "0hJiHye/blog_project",
		  "0hJiHye/danim",
		  "0hJiHye/danim.",
		  "0hJiHye/firstsiteproject",
		  "0hJiHye/firstsiteprojects",
		  "0hJiHye/new_Github",
		  "metatron-app/metatron-discovery"
		],
		"count": 14,
		"사용자종류": null,
		"login": "0hJiHye",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-04-14 15:41:50.000+0900"
	  },
	  {
		"meta": 10,
		"repos": [
		  "0x00000FF/-",
		  "0x00000FF/.emacs.d",
		  "0x00000FF/98shell",
		  "0x00000FF/ARIA.NET",
		  "0x00000FF/Bookshelf",
		  "0x00000FF/CPU-Homework",
		  "0x00000FF/DOSFramework",
		  "0x00000FF/DaechungCon-Prepared-Statement",
		  "0x00000FF/Docs.ko-kr",
		  "0x00000FF/Emuera",
		  "0x00000FF/GhidraNET",
		  "0x00000FF/Hardcode",
		  "0x00000FF/HitomiParser",
		  "0x00000FF/JokeRansom-Decode",
		  "0x00000FF/KIN",
		  "0x00000FF/KLLU",
		  "0x00000FF/Leetcode",
		  "0x00000FF/Lycoris",
		  "0x00000FF/MS-DOS",
		  "0x00000FF/MockInterview",
		  "0x00000FF/PEngine",
		  "0x00000FF/SEED.NET",
		  "0x00000FF/SICPwFS",
		  "0x00000FF/SickzilSFMLUI",
		  "0x00000FF/System.Security.Cryptography.KISA",
		  "0x00000FF/TIS-100",
		  "0x00000FF/TMaxOS-Fork",
		  "0x00000FF/ToughC",
		  "0x00000FF/TripNAS",
		  "0x00000FF/Tvple_Eraser",
		  "0x00000FF/cherry-bbs-remain",
		  "0x00000FF/cnu-cse-assignments",
		  "0x00000FF/codentalks-discordbot",
		  "0x00000FF/conoha-api-helper",
		  "0x00000FF/coreclr",
		  "0x00000FF/data-structures",
		  "0x00000FF/discord-cli",
		  "0x00000FF/enigma-pi",
		  "0x00000FF/essentials",
		  "0x00000FF/hanja-coding",
		  "0x00000FF/iopool",
		  "0x00000FF/justforfun",
		  "0x00000FF/kotoshokan-engine",
		  "0x00000FF/libhwpnet",
		  "0x00000FF/motherboard-survey-kr",
		  "0x00000FF/my-settings",
		  "0x00000FF/nonstop-programming-2018",
		  "0x00000FF/philosophers-stone",
		  "0x00000FF/rensenware",
		  "0x00000FF/rensenware.github.com",
		  "0x00000FF/rensenware.github.io",
		  "0x00000FF/rensenware_force",
		  "0x00000FF/renzeulware",
		  "0x00000FF/silent-selene",
		  "0x00000FF/studyforus-aspnet-core-lect",
		  "0x00000FF/toeic-study-record",
		  "0x00000FF/unixv6-x86",
		  "0x00000FF/vPn",
		  "0x00000FF/vim-linecount",
		  "0x00000FF/wargame",
		  "Alex4386/rensen-richpresence",
		  "Alex4386/turnoff-namuwiki",
		  "Cheatinikle/MD5Battle_OLD_VERSION",
		  "CosmosOS/Cosmos",
		  "I-CAST-AlphaDev/MovieSupport",
		  "JasonShin/reason-vue",
		  "JsSucks/BetterDiscordApp",
		  "KUR-creative/SickZil-Machine",
		  "KUR-creative/sick-zil-machine",
		  "Microsoft/MS-DOS",
		  "Microsoft/dotnet",
		  "Red-Portal/thread-pool-benchmark",
		  "ValdikSS/GoodbyeDPI",
		  "aspnet/Docs.ko-kr",
		  "codentalks/CodeNDocs",
		  "dc-koromo/koromo-copy",
		  "dotnet/core",
		  "dotnet/coreclr",
		  "dotnet/corefx",
		  "dotnet/roslyn",
		  "hendricius/pizza-dough",
		  "kkamagui/mint64os",
		  "krta2/awesome-nonsan",
		  "metatron-app/metatron-discovery",
		  "microsoft/Terminal",
		  "microsoft/terminal",
		  "noodlebox/betterdiscord-plugins",
		  "pdpdds/allegro4_dos",
		  "pengine-project/PEngineCore",
		  "postgres/postgres",
		  "ps64project/kernel",
		  "ps64project/kernel-legacy",
		  "ps64project/ps64project.github.io",
		  "tmaxcloud/tmaxos",
		  "utilForever/AlphaGo-tutorial",
		  "utilForever/BabaIsAuto",
		  "utilForever/DiscoveringTheModernCpp",
		  "wotmd/AFF-2019-solution",
		  "xpressengine/xe-core"
		],
		"count": 542,
		"사용자종류": null,
		"login": "0x00000FF",
		"type": [
		  "IssueCommentEvent",
		  "WatchEvent"
		],
		"_time": "2018-01-01 11:09:09.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "10000ceo",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-17 05:44:08.000+0900"
	  },
	  {
		"meta": 2,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 2,
		"사용자종류": null,
		"login": "1221pss",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-29 08:29:48.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "1ambda/1ambda.github.io",
		  "1ambda/jupyter-catalog",
		  "1ambda/practical-data-pipeline",
		  "1ambda/recommendation-system",
		  "1ambda/terraform-aws-eks-jupyterhub",
		  "AlexsJones/kubernetes-nifi-cluster",
		  "AppsFlyer/kafka-mirror-tester",
		  "Azure/mmlspark",
		  "BlazingDB/pyBlazing",
		  "GoogleCloudPlatform/tensorflow-lifetime-value",
		  "GoogleContainerTools/skaffold",
		  "IBM/kui",
		  "IDSIA/sacred",
		  "Yelp/elastalert",
		  "adilkhash/Data-Engineering-HowTo",
		  "agalwood/Motrix",
		  "andrewrothstein/ansible-kafka",
		  "andrewrothstein/ansible-kafka-broker",
		  "andromedarabbit/dotfiles",
		  "apache/incubator-hudi",
		  "apache/sentry",
		  "awskrug/datascience-group",
		  "awslabs/kinesis-kafka-connector",
		  "bojand/ghz",
		  "casbin/awesome-auth",
		  "casbin/jcasbin",
		  "codertimo/BERT-pytorch",
		  "confluentinc/confluent-kafka-python",
		  "confluentinc/cp-ansible",
		  "containous/yaegi",
		  "danielcoman/kubernetes-uReplicator",
		  "danielfrg/s3contents",
		  "danielqsj/kafka_exporter",
		  "druid-io/RDruid",
		  "druid-io/pydruid",
		  "elastic/ansible-elasticsearch",
		  "explosion/jupyterlab-prodigy",
		  "fullstorydev/grpcui",
		  "geerlingguy/ansible-role-logstash",
		  "gnes-ai/gnes",
		  "godatadriven/druid-ansible",
		  "google/wire",
		  "graykode/aws-kubeadm-terraform",
		  "heartexlabs/label-studio",
		  "hjacobs/kube-job-cleaner",
		  "hongsii/mart-holiday-alarm",
		  "horovod/horovod",
		  "humio/ansible-kafka",
		  "itmare/es_lecture",
		  "jaytaylor/ansible-kafka",
		  "jcasbin/jdbc-adapter",
		  "jeongyoonlee/Kaggler",
		  "jupyter/repo2docker",
		  "kefranabg/readme-md-generator",
		  "kesuskim/Front-End-Checklist",
		  "klaussinani/hyperocean",
		  "klaussinani/qoa",
		  "klaussinani/signale",
		  "klaussinani/taskbook",
		  "kube-aws/kube-spot-termination-notice-handler",
		  "kubedb/elasticsearch",
		  "kubernetes-sigs/dashboard-metrics-scraper",
		  "livegrep/livegrep",
		  "logstash-plugins/logstash-output-kafka",
		  "makinarocks/awesome-industrial-machine-datasets",
		  "maruel/panicparse",
		  "metamx/druid-spark-batch",
		  "metatron-app/metatron-discovery",
		  "microsoft/tensorwatch",
		  "nalbam/terraform-aws-elasticsearch",
		  "nexeck/homebrew-tmuxinator",
		  "nhn/toast-ui.vue-chart",
		  "noam3127/github-code-folding",
		  "onaio/ansible-druid",
		  "onaio/ansible-tranquility",
		  "ops-guru/og-helm-kafka-mm",
		  "prometheus/jmx_exporter",
		  "prometheus/node_exporter",
		  "pullreminders/slack-action",
		  "pusher/k8s-spot-rescheduler",
		  "rgburke/grv",
		  "ricklamers/gridstudio",
		  "ridi/style-guide",
		  "rk2900/bidding-machine",
		  "sansible/kafka",
		  "sindresorhus/refined-github",
		  "sleighzy/ansible-kafka",
		  "sleighzy/ansible-zookeeper",
		  "soofaloofa/imply-ansible",
		  "tailwindcss/tailwindcss",
		  "timqian/chart.xkcd",
		  "torreswoo/EDA-nyc-taxi",
		  "uber/h3",
		  "uber/uReplicator",
		  "ucbrise/clipper",
		  "unchartedsky/dockerized-ureplicator",
		  "vivekratnavel/omniboard",
		  "w0lfschild/Flashlight",
		  "yoonkt200/recommender-system",
		  "zalando/connexion"
		],
		"count": 1479,
		"사용자종류": null,
		"login": "1ambda",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-01-03 04:52:57.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "1eedaegon/1eedaegon.github.com",
		  "1eedaegon/1eedaegon.github.io",
		  "1eedaegon/1eedaegon.io",
		  "1eedaegon/DataScience",
		  "1eedaegon/DevOps",
		  "1eedaegon/DjangoProject",
		  "1eedaegon/Jamcoding",
		  "1eedaegon/KYLius-method",
		  "1eedaegon/ML-DL-with-tensorflow",
		  "1eedaegon/NSML",
		  "1eedaegon/Python",
		  "1eedaegon/R-analaysis",
		  "1eedaegon/Robo-advisor",
		  "1eedaegon/Writing",
		  "1eedaegon/ai-hackathon-2018",
		  "1eedaegon/centrarium",
		  "1eedaegon/it_project",
		  "1eedaegon/keras-docs-ko",
		  "1eedaegon/paper-review",
		  "1eedaegon/simple-search-engine",
		  "1eedaegon/solveC-",
		  "TAEHYOKIM/INGYEOMENTAL",
		  "alanorth/hugo-theme-bootstrap4-blog",
		  "bencentra/centrarium",
		  "cheese10yun/github-project-management",
		  "chesterhow/tale",
		  "cs231n/cs231n.github.io",
		  "deep-diver/Machine-Learning-Yearning-Korean-Translation",
		  "dirkfabisch/mediator",
		  "fongandrew/hydeout",
		  "galexrt/k8s-vagrant-multi-node",
		  "isme2n/isme2n.github.io",
		  "jakevdp/PythonDataScienceHandbook",
		  "janghyeonan/it_project",
		  "jhfjhfj1/autokeras",
		  "junhobaik/junhobaik.github.io",
		  "keras-team/keras-docs-ko",
		  "kimgyuhyun/workspace",
		  "kmario23/deep-learning-drizzle",
		  "kyliusmethod/Recommandation-algorithms",
		  "kyliusmethod/paper-review",
		  "likejazz/simple-search-engine",
		  "linux-audit/audit-documentation",
		  "matplotlib/matplotlib",
		  "metatron-app/metatron-discovery",
		  "mmistakes/skinny-bones-jekyll",
		  "naver/ai-hackathon-2018",
		  "nhn/tui.editor",
		  "nrandecker/particle",
		  "okjsp/okky",
		  "okjsp/okmakeover",
		  "rickiepark/handson-ml",
		  "rootsongjc/kubernetes-vagrant-centos-cluster",
		  "scikit-learn/scikit-learn",
		  "smallerhand/KYLius-method",
		  "smallerhand/newbie",
		  "tensorflow/docs",
		  "tensorflow/tensorflow",
		  "tensorflowkorea/tensorflow-kr",
		  "terryum/awesome-deep-learning-papers",
		  "vegas-viz/Vegas",
		  "vuejs/vuepress",
		  "yoonkim/CNN_sentence"
		],
		"count": 175,
		"사용자종류": null,
		"login": "1eedaegon",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-03-20 13:08:55.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "1jessy1",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-26 05:56:27.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "2005austin",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-18 05:24:58.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "2008jung",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-28 06:36:23.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "2hongmimi",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-28 14:49:31.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "4na2no1",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-26 01:59:38.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "4thepoch/4thepoch.github.io",
		  "4thepoch/ARIA",
		  "4thepoch/LearnVue",
		  "4thepoch/RL_OPT_RWC",
		  "4thepoch/RWC_RL_ALGORITHM",
		  "4thepoch/hjchoi.github.io",
		  "4thepoch/iREMS",
		  "4thepoch/keras",
		  "4thepoch/web1",
		  "awjuliani/DeepRL-Agents",
		  "biospin/BigBio",
		  "dennybritz/reinforcement-learning",
		  "kakao/khaiii",
		  "keras-team/keras",
		  "kmario23/deep-learning-drizzle",
		  "markmo/dltemplate",
		  "mas-at-bath/bsf",
		  "maxim5/hyper-engine",
		  "metatron-app/metatron-discovery",
		  "mmistakes/hpstr-jekyll-theme",
		  "mmistakes/minimal-mistakes",
		  "mmistakes/mm-github-pages-starter",
		  "openai/universe-starter-agent",
		  "pekaalto/sc2aibot"
		],
		"count": 117,
		"사용자종류": null,
		"login": "4thepoch",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-01-22 05:10:11.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "5unKn0wn/5unKn0wn.github.io",
		  "5unKn0wn/5unkn0wn.github.io",
		  "5unKn0wn/baekjoon",
		  "5unKn0wn/basic-reversing",
		  "5unKn0wn/ctfs",
		  "L4ys/CTF",
		  "anch0vy/hi",
		  "chall-stypr-deploy/chall.stypr.com",
		  "david942j/ctf-writeups",
		  "david942j/seccomp-tools",
		  "ele7enxxh/android-afl",
		  "epinna/tplmap",
		  "junorouse/ctf",
		  "mathboy7/CTF",
		  "metatron-app/metatron-discovery",
		  "push0ebp/api-deobfuscator",
		  "pwning/public-writeup",
		  "sea0breeze/ctf",
		  "utilForever/RosettaStone",
		  "yunnim/EVMDBG"
		],
		"count": 109,
		"사용자종류": null,
		"login": "5unKn0wn",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-02-08 06:52:52.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "75gloria",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-28 14:42:56.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "8luebottle/Baby_Tiger",
		  "8luebottle/Miniter",
		  "8luebottle/blog",
		  "8luebottle/hello-git",
		  "8luebottle/movieApp",
		  "BoyCook/TwitterJSClient",
		  "CodingGarden/meower",
		  "EbookFoundation/free-programming-books",
		  "TheAlgorithms/Java",
		  "airbnb/javascript",
		  "babel/babel",
		  "cdnjs/cdnjs",
		  "cs50/python-cs50",
		  "devJang/developer-roadmap",
		  "facebook/react",
		  "gatsbyjs/gatsby",
		  "geonhwiii/IAT_EXAMPLE",
		  "getify/You-Dont-Know-JS",
		  "jashkenas/underscore",
		  "joyofclojure/book-source",
		  "jupyter/jupyter",
		  "kentcdodds/advanced-react-hooks",
		  "kentcdodds/learn-react-hooks",
		  "kesuskim/Front-End-Checklist",
		  "metatron-app/metatron-discovery",
		  "netlify/netlify-cms",
		  "pgbovine/OnlinePythonTutor",
		  "taniarascia/taniarascia.com",
		  "trebonian/visual6502",
		  "twbs/bootstrap",
		  "ulfrid/django-api-exam",
		  "ulfrid/hello-git",
		  "vanilla-coding/prep-guide",
		  "workshopper/javascripting",
		  "yjs03057/33-js-concepts"
		],
		"count": 168,
		"사용자종류": null,
		"login": "8luebottle",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-03-28 05:14:41.000+0900"
	  },
	  {
		"meta": 19,
		"repos": [
		  "9bow/ARMemNet",
		  "9bow/FBDocsType1",
		  "9bow/FBDocsType2",
		  "9bow/FBTestRepo",
		  "9bow/PyTorch-tutorials-kr",
		  "9bow/Seoul-MatZip-2019",
		  "9bow/hello-github-actions",
		  "9bow/pytorch_sphinx_theme",
		  "9bow/spoqa-pycon-2019-code-challenge",
		  "9bow/tutorials",
		  "ChangJoo-Park/flutter_plugin_helloworld",
		  "ChangJoo-Park/universal-nuxt-repository",
		  "Geo-Joy/Deep-Learning-for-Time-Series-Forecasting",
		  "HIPS/author-roulette",
		  "HyOsori/Osori-Website",
		  "IntelPython/daal4py",
		  "IntelPython/scikit-learn_bench",
		  "KakaoBrain/fast-autoaugment",
		  "KurochkinAlexey/Hierarchical-Attention-Based-Recurrent-Highway-Networks-for-Time-Series-Prediction",
		  "LeCoupa/awesome-cheatsheets",
		  "OpenbookOrg/openbook-app",
		  "StylishThemes/GitHub-Dark",
		  "UrbanInstitute/pyspark-tutorials",
		  "actions/starter-workflows",
		  "advaitsave/Introduction-to-Time-Series-forecasting-Python",
		  "antirez/redis",
		  "bharathgs/Awesome-pytorch-list",
		  "capablemonkey/github-go-to-definition",
		  "chickenbestlover/RNN-Time-series-Anomaly-Detection",
		  "comfuture/actions",
		  "comfuture/nuxt-firebase",
		  "cstorm125/viztech",
		  "dafrie/lstm-load-forecasting",
		  "databricks/spark-csv",
		  "densitydesign/raw",
		  "drabastomek/learningPySpark",
		  "eva-design/eva",
		  "facebook/rocksdb",
		  "floodsung/Deep-Learning-Papers-Reading-Roadmap",
		  "flutter/flutter",
		  "flutter/samples",
		  "ft-interactive/chart-doctor",
		  "gchq/CyberChef",
		  "hiroppy/fusuma",
		  "hugapi/hug",
		  "huggingface/pytorch-pretrained-BERT",
		  "idjoopal/BurgerIndex2019",
		  "intel-analytics/BigDL",
		  "intel-analytics/analytics-zoo",
		  "jojoldu/junior-recruit-scheduler",
		  "jsbroks/awesome-dataset-tools",
		  "kamranahmedse/git-standup",
		  "kivy/pyjnius",
		  "knadh/listmonk",
		  "libra/libra",
		  "lorenzodifuccia/safaribooks",
		  "lutzroeder/netron",
		  "metatron-app/metatron-discovery",
		  "microsoft/CNTK",
		  "microsoft/tensorwatch",
		  "mkdocs/mkdocs",
		  "mnms/ARMemNet",
		  "mnms/ARMemNet-BigDL",
		  "moemen95/Pytorch-Project-Template",
		  "nonexistorgfortesting/nonactiverepository",
		  "ovity/octotree",
		  "paperswithcode/paperswithcode-data",
		  "paperswithcode/sota-extractor",
		  "phiresky/ripgrep-all",
		  "pjreddie/darknet",
		  "pytorch/audio",
		  "pytorch/pytorch_sphinx_theme",
		  "pytorch/tutorials",
		  "ricklamers/gridstudio",
		  "ritchieng/the-incredible-pytorch",
		  "sachaos/note",
		  "sbrugman/deep-learning-papers",
		  "shineware/KOMORANAdmin",
		  "shineware/PyKOMORAN",
		  "shineware/blog",
		  "southkorea/southkorea-maps",
		  "sphinx-doc/sphinx",
		  "spoqa/spoqa-pycon-2019-code-challenge",
		  "sryza/spark-timeseries",
		  "steve228uk/YouTube-Music",
		  "stewartmcgown/uds",
		  "sveltejs/svelte",
		  "taltal-ddj/taltal",
		  "telescopejs/telescope",
		  "tensorflow/models",
		  "thenaturalist/awesome-business-intelligence",
		  "timgrossmann/InstaPy",
		  "valeriansaliou/sonic",
		  "vuejs/vue-hackernews-2.0",
		  "vuski/admdongkor",
		  "xephonhq/awesome-time-series-database",
		  "yandex/ClickHouse",
		  "yangshun/tech-interview-handbook",
		  "youknowone/ring",
		  "zihangdai/xlnet"
		],
		"count": 1328,
		"사용자종류": "contributor",
		"login": "9bow",
		"type": [
		  "ForkEvent",
		  "IssueCommentEvent",
		  "IssuesEvent",
		  "WatchEvent"
		],
		"_time": "2018-01-04 01:10:28.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "AhnJG/AWS",
		  "AhnJG/Algorithm",
		  "AhnJG/Algorithm_Python",
		  "AhnJG/Auto_navercafe_attendance",
		  "AhnJG/Basic_Ajax",
		  "AhnJG/Basic_Java",
		  "AhnJG/Basic_JavaScript",
		  "AhnJG/Basic_Node.js",
		  "AhnJG/Basic_Node.js-",
		  "AhnJG/DeepLearning",
		  "AhnJG/Eng-Kor-Dictionary-Search-in-Linux-CLI",
		  "AhnJG/Finedust-and-Weather-Forecast",
		  "AhnJG/Java_Basic",
		  "AhnJG/Kor-Eng-Dictionary-Search-in-Linux-CLI",
		  "AhnJG/Links",
		  "AhnJG/Programming-Language",
		  "AhnJG/Study",
		  "AhnJG/Travel_Info_Website",
		  "AhnJG/graphql_test",
		  "AhnJG/web_shoseo",
		  "AhnJG/whiteHat",
		  "Haru9029/whiteHat",
		  "InSpaceAI/RL-InDrone",
		  "JJoriping/KKuTu",
		  "NextGroup/NodeTutorial",
		  "Team-Neighborhood/I-want-to-study-Data-Science",
		  "TheAlgorithms/Python",
		  "Unity-Technologies/ml-agents",
		  "ZeroCho/nodejs-book",
		  "cheese10yun/node-yun",
		  "chrislgarry/Apollo-11",
		  "davidsandberg/facenet",
		  "geekcomputers/Python",
		  "gilbutITbook/006975",
		  "matiassingers/awesome-readme",
		  "metatron-app/metatron-discovery",
		  "nigayo/node_server_inflearn",
		  "rickiepark/deep-learning-with-python-notebooks",
		  "sjjeong/android-tech-spec-in-korea-company",
		  "tensorflow/tensorflow",
		  "tomasr/molokai"
		],
		"count": 217,
		"사용자종류": null,
		"login": "AhnJG",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-05-04 18:14:02.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "8percent/django-orm-cookbook-ko",
		  "AhnSeongHyun/Flask-MQTT",
		  "AhnSeongHyun/Meier",
		  "AhnSeongHyun/ahnseognhyun.github.io",
		  "AhnSeongHyun/aiohttp_example",
		  "AhnSeongHyun/akka-http-example",
		  "AhnSeongHyun/awesome-blogs",
		  "AhnSeongHyun/cookiecutter",
		  "AhnSeongHyun/flask-upload-limit",
		  "AhnSeongHyun/git_test",
		  "AhnSeongHyun/graphene",
		  "AhnSeongHyun/meier",
		  "AhnSeongHyun/platter",
		  "AhnSeongHyun/python",
		  "AhnSeongHyun/requests-html",
		  "AhnSeongHyun/settings",
		  "AhnSeongHyun/sqlalchemy_customtypes_example",
		  "AhnSeongHyun/sqlalchemy_customtypes_test",
		  "AhnSeongHyun/study",
		  "AhnSeongHyun/tt",
		  "BenjaminKim/awesome-blogs",
		  "EBvi/dev-matrix",
		  "HomoEfficio/dev-tips",
		  "JeaSungLEE/bundang",
		  "JungWinter/chatterbox",
		  "MalphasWats/flask-blueprint-loader",
		  "Medium/medium-sdk-python",
		  "MobileTribe/commit-template-idea-plugin",
		  "NVIDIA/FastPhotoStyle",
		  "Rainist/cookiecutter-sanic",
		  "Rainist/python",
		  "Rainist/styleguide",
		  "RazerM/sqlalchemy_aio",
		  "Redocly/redoc",
		  "RussBaz/enforce",
		  "TryGhost/Ghost",
		  "TwoLaid/python-sqlparser",
		  "aaugustin/websockets",
		  "actix/actix-web",
		  "agemor/korean-name-generator",
		  "arialdomartini/Back-End-Developer-Interview-Questions",
		  "arogozhnikov/python3_with_pleasure",
		  "audreyr/cookiecutter",
		  "brix/crypto-js",
		  "crazyguitar/pysheeet",
		  "datayanolja/opensource-dmz-bus",
		  "dev-meetup/dev-meetup.github.io",
		  "dgilland/pushjack",
		  "elastic7327/flask-app",
		  "emqtt/emqttd",
		  "encode/databases",
		  "erm/loamy",
		  "facebook/react",
		  "fantix/gino",
		  "floyernick/fleep-py",
		  "foundweekends/giter8",
		  "gawel/pyquery",
		  "glamp/bashplotlib",
		  "google/budou",
		  "google/pytype",
		  "graphql-python/flask-graphql",
		  "graphql-python/graphene",
		  "hashicorp/hcl",
		  "howtographql/howtographql",
		  "instacart/lore",
		  "jlfwong/speedscope",
		  "joeseonmi/woosan_weather",
		  "kam6512/Tessy",
		  "kennethreitz/requests-html",
		  "kesuskim/Front-End-Checklist",
		  "kitao/pyxel",
		  "leehosung/awesome-devteam",
		  "lepture/flask-wtf",
		  "lqez/rogrepos",
		  "magmax/python-inquirer",
		  "matiastucci/vue-input-tag",
		  "meier-project/meier",
		  "meier-project/migration",
		  "metatron-app/metatron-discovery",
		  "naver/billboard.js",
		  "nhnent/tui.grid",
		  "nikitavoloboev/my-mac-os",
		  "pybuilder/pybuilder",
		  "pycampers/zproc",
		  "pypa/twine",
		  "pytest-dev/pytest-flask",
		  "python-mondrian/mondrian",
		  "requests/requests",
		  "robinhood/faust",
		  "seanpar203/sanic-starter",
		  "shieldfy/API-Security-Checklist",
		  "sindresorhus/refined-github",
		  "stlehmann/Flask-MQTT",
		  "sujinleeme/the-road-to-learn-react-korean",
		  "tqdm/tqdm",
		  "wouterken/codility-python",
		  "youknowone/ring",
		  "younari/tastySwift",
		  "youngrok/poi4py",
		  "yunho0130/awesome-blockchain-kor"
		],
		"count": 570,
		"사용자종류": null,
		"login": "AhnSeongHyun",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-01-02 08:25:50.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "AiOO/core",
		  "AiOO/dotfiles",
		  "AiOO/libplanet-explorer",
		  "AiOO/libplanet-explorer-frontend",
		  "AiOO/nirum",
		  "AiOO/postgresql-backup",
		  "KimWooHyun/WHLunarCalendar",
		  "KimWooHyun/vue-lunar-calendar",
		  "admire93/beer-frontend",
		  "admire93/beer.ts",
		  "boto/boto",
		  "dotnet/core",
		  "metatron-app/metatron-discovery",
		  "microsoft/Terminal",
		  "microsoft/WSL",
		  "mintty/wsltty",
		  "nirum-lang/nirum-python",
		  "pbzweihander/rust-trending",
		  "planetarium/libplanet-explorer",
		  "planetarium/libplanet-explorer-frontend",
		  "planetarium/libplanet.net",
		  "rprichard/wslbridge",
		  "rustasync/http-service",
		  "sokcuri/ChromeXP",
		  "spoqa/geofront",
		  "spoqa/nirum",
		  "spoqa/postgresql-backup",
		  "sqlalchemy/alembic",
		  "vimwiki/vimwiki",
		  "webcompat/web-bugs"
		],
		"count": 74,
		"사용자종류": null,
		"login": "AiOO",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-02-09 15:59:22.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "Aishelre/RNN-prediction",
		  "Aishelre/blog_post",
		  "Aishelre/cafe-filter-extension",
		  "Aishelre/cafe-post-save",
		  "Aishelre/de-post",
		  "Aishelre/de-post-daily",
		  "Aishelre/django-movieblog",
		  "Aishelre/django-practice",
		  "Aishelre/engineering-mathematics-HW",
		  "Aishelre/flask-microblog",
		  "Aishelre/flask-oauth-snippet",
		  "Aishelre/flask_api_doc_templates",
		  "Aishelre/gittest",
		  "Aishelre/hello",
		  "Aishelre/hello_",
		  "Aishelre/movieblog",
		  "Aishelre/oauth-snippet",
		  "Aishelre/pyTracer",
		  "Aishelre/removed-post",
		  "Aishelre/shop",
		  "Aishelre/system_trading",
		  "Aishelre/test-root",
		  "Aishelre/test-sub",
		  "Aishelre/time-util",
		  "Aishelre/tkinter-Minesweeper",
		  "Aishelre/web_hw",
		  "Chive/django-multiupload",
		  "RafeKettler/magicmethods",
		  "Robpol86/Flask-Large-Application-Example",
		  "Semantic-Org/Semantic-UI",
		  "YoongiKim/AutoCrawler",
		  "binance-exchange/binance-official-api-docs",
		  "gorhill/uBlock",
		  "gothinkster/realworld",
		  "hcgnine/Developer-Roadmap",
		  "jamescooke/restapidocs",
		  "jmoiron/humanize",
		  "junegunn/fzf",
		  "kennethreitz/requests",
		  "liks79/flask",
		  "ltbl/py-phash",
		  "metatron-app/metatron-discovery",
		  "secdev/scapy"
		],
		"count": 245,
		"사용자종류": null,
		"login": "Aishelre",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-01-01 08:25:05.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "0x00000FF/DaechungCon-Prepared-Statement",
		  "0x00000FF/TMaxOS-Fork",
		  "Alex4386/CIRNO",
		  "Alex4386/KR-censorship-190211",
		  "Alex4386/STGEngineX",
		  "Alex4386/baekjoon-archive",
		  "Alex4386/gachon-autoregister-course",
		  "Alex4386/linear-regression-from-scratch",
		  "Alex4386/nyong-studio",
		  "Alex4386/pay1oad-PE-parser",
		  "Alex4386/pe-parser",
		  "Alex4386/rensen-connect",
		  "Alex4386/rensen-richpresence",
		  "Alex4386/rnn-from-scratch",
		  "Alex4386/temp",
		  "Alex4386/tensorflow-without-a-phd",
		  "Alex4386/turnoff-namuwiki",
		  "Alex4386/uth05win",
		  "DevYourK/karaokeParser",
		  "Doro-nyong/nyong-studio",
		  "JesusFreke/smali",
		  "Lanchon/haystack",
		  "NVlabs/stylegan",
		  "Seia-Soto/invisibleHandshake",
		  "SortableJS/Vue.Draggable",
		  "Team-StarGarden/darakbang-kodic-crawler",
		  "Team-StarGarden/express-phpify",
		  "TeamLab/Gachon_CS50_Python_KMOOC",
		  "Wintiger0222/uth05win",
		  "ageron/handson-ml",
		  "bemusic/bemuse",
		  "bitinn/node-fetch",
		  "carykh/jumpcutter",
		  "cdr/code-server",
		  "cdr/sshcode",
		  "cokia/2019-seoul-hardware-hackathon-jeomjjigi-",
		  "cokia/ARDATAPI",
		  "cokia/ARP-Spoofer",
		  "cokia/Casper_consensus_Game",
		  "cokia/Dust_Client-app-",
		  "cokia/ETHSNAIL",
		  "cokia/SwiftUI-Login-page",
		  "cokia/SwiftUI-cheatsheet-kor",
		  "cokia/TWIL-pwnable",
		  "cokia/azure-iot-sdk-c",
		  "cokia/docs",
		  "cokia/draft",
		  "cokia/ethcon-korea-2019-pdf",
		  "cokia/ethereum-lists",
		  "cokia/flask-gmail-api",
		  "cokia/flask-login",
		  "cokia/iot-portal",
		  "cokia/ipfs-example",
		  "cokia/korean-bad-words",
		  "cokia/pomodoro-timer",
		  "cokia/pomodoro-timer-react-native",
		  "cokia/python-docs-ko",
		  "cokia/rchain",
		  "cokia/server-icon-html",
		  "cokia/shiny-potato",
		  "cokia/simpleEthereumExplorer",
		  "cokia/ublox-odin-evk-w2-azure-iothub",
		  "cokia/url-shorter",
		  "danieluhm/kongblocks",
		  "danieluhm/pyUpdater",
		  "daybrush/scenejs",
		  "des5141/AnzuFutaba",
		  "electron/electron",
		  "firamath/firamath",
		  "hooni1806/temp",
		  "iamdustan/smoothscroll",
		  "jakubroztocil/httpie",
		  "metatron-app/metatron-discovery",
		  "microsoft/Terminal",
		  "microsoft/TypeScript",
		  "nicholastay/passport-discord",
		  "nvbn/thefuck",
		  "otya128/winevdm",
		  "park012241/turnoff-namuwiki-firefox",
		  "powroupi/blender_mmd_tools",
		  "ppy/osu",
		  "seemoo-lab/opendrop",
		  "sharkyh20/KinectToVR",
		  "shiftpsh/sgcs-cse3013",
		  "shiftpsh/solvedac-chrome",
		  "tensorflow/models",
		  "tensorflow/tensorflow",
		  "theia-ide/theia",
		  "winstar0070/FTP-Panel",
		  "winstar0070/HongSeeBot",
		  "winstar0070/Reverse-Engineering-Tutorials",
		  "winstar0070/crong.github.io",
		  "winstar0070/esxi-simple-web",
		  "winstar0070/onepage-scroll",
		  "winstar0070/tfjs-models",
		  "winstar0070/tistory_markdown_highlight",
		  "winstar0070/web",
		  "yenchenlin/DeepLearningFlappyBird",
		  "yeonit/yeonit",
		  "yui540/Cowardly-Witch"
		],
		"count": 1029,
		"사용자종류": null,
		"login": "Alex4386",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-01-10 15:20:39.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "MLnick/elasticsearch-vector-scoring",
		  "bab2min/Kiwi",
		  "elastic/elasticsearch",
		  "kakao/elasticsearch-shard-suggester",
		  "lior-k/fast-elasticsearch-vector-scoring",
		  "metatron-app/metatron-discovery"
		],
		"count": 6,
		"사용자종류": null,
		"login": "AnSungHyun",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-11-02 05:13:58.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "1ambda/terraform-all-in-one",
		  "AUSG/ausg-seminar-2019",
		  "AndersonChoi/AndersonChoi.github.io",
		  "AndersonChoi/Hackathon-Manual",
		  "AndersonChoi/Helicoaster",
		  "AndersonChoi/andersonchoi.github.com",
		  "AndersonChoi/animated-custom-listview-example",
		  "AndersonChoi/clay",
		  "AndersonChoi/coalamovement",
		  "AndersonChoi/git-sync",
		  "AndersonChoi/goQuality-dev-contents",
		  "AndersonChoi/kafka",
		  "AndersonChoi/medium-tech-blog",
		  "AndersonChoi/rake-android",
		  "AndersonChoi/scalatra",
		  "AndersonChoi/sentinel-document",
		  "AndersonChoi/smartone-hackathon",
		  "AndersonChoi/wedding-card",
		  "BenjaminKim/awesome-blogs",
		  "Homebrew/homebrew-cask",
		  "Integerous/goQuality-dev-contents",
		  "JaeYeopHan/Interview_Question_for_Beginner",
		  "KMU-OSS-Laboratory/Hackathon-Manual",
		  "RichardLitt/standard-readme",
		  "SeTeM/pync",
		  "TheOpenCloudEngine/uEngine-cloud-k8s",
		  "TuneOSS/sdk-release",
		  "anseki/leader-line",
		  "apache/kafka",
		  "apache/predictionio",
		  "apache/zookeeper",
		  "aseigneurin/kafka-tutorial-simple-client",
		  "athityakumar/colorls",
		  "confluentinc/ksql",
		  "enshahar/BasicFPinScala",
		  "evonit/bigdata-general-practice",
		  "freepsw/kafka-monitoring",
		  "google/code-prettify",
		  "hashicorp/terraform",
		  "hatemogi/semver",
		  "hongsii/mart-holiday-alarm",
		  "hunkydory824/wedding-card",
		  "influxdata/telegraf",
		  "istio/istio.io",
		  "jmxtrans/jmxtrans",
		  "jojoldu/junior-recruit-scheduler",
		  "joway/burrow-dashboard",
		  "kakao/awesome-tech-newletters",
		  "kkangseongyun/kkangs_kotlin",
		  "knight1128/scalatra-gradle-helloworld",
		  "kubernetes/dashboard",
		  "kubernetes/git-sync",
		  "kubernetes/kubernetes",
		  "leehosung/awesome-devteam",
		  "lihaoyi/cask",
		  "line/clay",
		  "linkedin/Burrow",
		  "metatron-app/metatron-discovery",
		  "mgcation/AWS-Chatbot-KR-Simple-Guide",
		  "milooy/remote-or-flexible-work-company-in-korea",
		  "mixpanel/mixpanel-android",
		  "mlflow/mlflow",
		  "naver/android-imagecropview",
		  "naver/billboard.js",
		  "nono5546/Timeline_React",
		  "oaksong/developers-retrospective",
		  "othneildrew/Best-README-Template",
		  "peterko5236/kafka",
		  "progit/progit2",
		  "ricklamers/gridstudio",
		  "robbyrussell/oh-my-zsh",
		  "sarojaba/awesome-devblog",
		  "sbt/sbt",
		  "sbt/sbt-assembly",
		  "sbt/website",
		  "scala-exercises/exercises-scalatutorial",
		  "scala/docs.scala-lang",
		  "scalatra/scalatra",
		  "scalatra/scalatra.g8",
		  "semver/semver.org",
		  "skpdi/rake-android",
		  "skpdi/rake-android-example",
		  "skpdi/rake-android-origin",
		  "skpdi/rake-document",
		  "skpdi/rake-iphone-example",
		  "skpdi/rake-iphone-origin",
		  "skpdi/rake-logger-android",
		  "skpdi/rake-server",
		  "skpdi/rake-window",
		  "skpdi/sentinel-document",
		  "sourcerer-io/sourcerer-app",
		  "spinnaker/halyard",
		  "spinnaker/spinnaker",
		  "squeryl/squeryl",
		  "ssonghey/wedding-card",
		  "stepanowon/mongo_script",
		  "stepanowon/vuejs_book_2nd",
		  "swapagarwal/swag-for-dev",
		  "syjdev/SYParallaxScrollView",
		  "tucan9389/medium-tech-blog"
		],
		"count": 340,
		"사용자종류": null,
		"login": "AndersonChoi",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-01-30 09:32:51.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "AndroidNetrunner/default",
		  "AndroidNetrunner/first_project",
		  "AndroidNetrunner/pleaseFinal",
		  "AndroidNetrunner/practiceProject",
		  "AndroidNetrunner/test",
		  "AndroidNetrunner/wwww",
		  "hufslikelion7/kby",
		  "metatron-app/metatron-discovery"
		],
		"count": 26,
		"사용자종류": null,
		"login": "AndroidNetrunner",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-01-19 18:41:25.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "Anhana",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-18 02:15:54.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "0voice/interview_internal_reference",
		  "AimeeLee77/keyword_extraction",
		  "Apollo2Mars/Algorithms-of-Artificial-Intelligence",
		  "Apollo2Mars/Basic-Programming-Skills",
		  "Apollo2Mars/Workspace-of-Conversation-AI",
		  "Apollo2Mars/Workspace-of-MRC",
		  "Apollo2Mars/Workspace-of-NLU",
		  "Apollo2Mars/Workspace-of-NN",
		  "Awesome-HarmonyOS/HarmonyOS",
		  "CLD2Owners/cld2",
		  "DataSystemsGroupUT/AutoML_Survey",
		  "EpistasisLab/tpot",
		  "EthicalML/awesome-production-machine-learning",
		  "Eurus-Holmes/Awesome_Multimodal_Research",
		  "HuaizhengZhang/Awesome-System-for-Machine-Learning",
		  "INTERMT/Awesome-PyTorch-Chinese",
		  "InsaneLife/Joint-NLU",
		  "LiyuanLucasLiu/RAdam",
		  "Maluuba/nlg-eval",
		  "Morizeyao/GPT2-Chinese",
		  "P2333/Papers-of-Robust-ML",
		  "RasaHQ/rasa",
		  "Roshanson/TextInfoExp",
		  "SKKSaikia/CS236_DGM",
		  "ShannonAI/Entity-Relation-As-Multi-Turn-QA",
		  "Urinx/RNAWorld",
		  "WING-NUS/sequicity",
		  "WillKoehrsen/Data-Analysis",
		  "YueYongDev/stopwords",
		  "alibaba/esim-response-selection",
		  "allenai/acl2018-semantic-parsing-tutorial",
		  "allenai/document-qa",
		  "alontalmor/MultiQA",
		  "alphadl/lookahead.pytorch",
		  "altercation/solarized",
		  "altercation/vim-colors-solarized",
		  "asyml/texar",
		  "attardi/wikiextractor",
		  "baidu-research/NCRF",
		  "baidu/Senta",
		  "benedekrozemberczki/awesome-gradient-boosting-papers",
		  "benedekrozemberczki/graph2vec",
		  "bojone/el-2019",
		  "bojone/keras_lookahead",
		  "chakki-works/doccano",
		  "codelucas/newspaper",
		  "cyk1337/PBT",
		  "cyk1337/Reinforcement-Learning-A-Simple-Tutorial",
		  "deepset-ai/FARM",
		  "dennybritz/deeplearning-papernotes",
		  "dennybritz/reinforcement-learning",
		  "dhwajraj/deep-siamese-text-similarity",
		  "didi/ChineseNLP",
		  "didi/delta",
		  "dmlc/gluon-nlp",
		  "dunovank/jupyter-themes",
		  "fastnlp/fastNLP",
		  "fchollet/deep-learning-models",
		  "fxsjy/jieba",
		  "github/gitignore",
		  "guotong1988/NLP-paper-for-work-together",
		  "haiker2011/awesome-nlp-sentiment-analysis",
		  "hankcs/HanLP",
		  "heartexlabs/awesome-data-labeling",
		  "hellerve/programming-talks",
		  "hscspring/All4NLP",
		  "huyingxi/Synonyms",
		  "iesl/dilated-cnn-ner",
		  "itchyny/vim-cursorword",
		  "jeongyoonlee/Kaggler",
		  "jindongwang/transferlearning",
		  "jiweil/Neural-Dialogue-Generation",
		  "keitakurita/Practical_NLP_in_PyTorch",
		  "kingtaurus/cs224d",
		  "lihanghang/Knowledge-Graph",
		  "liuchengxu/szuthesis",
		  "lonePatient/lookahead_pytorch",
		  "madrugado/Attention-Based-Aspect-Extraction",
		  "martian-ai/Awesome-Mathematics",
		  "martian-ai/Awesome-Paper",
		  "metatron-app/metatron-discovery",
		  "microsoft/DualLearning",
		  "msgi/nlp-journey",
		  "nghuyong/WeiboSpider",
		  "pytorch/examples",
		  "renll/StateNet",
		  "scutan90/CNN-Visualization",
		  "sfyc23/EverydayWechat",
		  "shibing624/similarity",
		  "sudharsan13296/Awesome-Meta-Learning",
		  "susanli2016/Machine-Learning-with-Python",
		  "taku910/crfpp",
		  "tensorflow/docs",
		  "thunlp/OpenKE",
		  "tuteng/Best-websites-a-programmer-should-visit-zh",
		  "xinychen/awesome-latex-drawing",
		  "ycm-core/YouCompleteMe",
		  "ymcui/Chinese-RC-Datasets",
		  "yzhao062/awesome-ensemble-learning",
		  "yzhao062/combo"
		],
		"count": 1822,
		"사용자종류": null,
		"login": "Apollo2Mars",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-01-02 05:16:36.000+0900"
	  },
	  {
		"meta": 2,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 2,
		"사용자종류": null,
		"login": "Ast3risk",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-29 09:09:17.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "AtumVRLab/gittutorial",
		  "metatron-app/metatron-discovery"
		],
		"count": 3,
		"사용자종류": null,
		"login": "AtumVRLab",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-05-17 00:30:49.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "Austin-Kayper",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-29 10:56:12.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "738/inko",
		  "BK-Choi/BK-Choi.github.io",
		  "BK-Choi/bk-choi.github.io",
		  "BK-Choi/study",
		  "LuisReinoso/git-history-browser-extension",
		  "OpenASR/idear",
		  "cheese10yun/spring-guide",
		  "exevil/Sketch-Export-Text",
		  "gharlan/alfred-github-workflow",
		  "metatron-app/metatron-discovery",
		  "naver/lucy-xss-filter",
		  "naverunion/naverunion.github.io",
		  "pegjs/pegjs",
		  "perillamint/GNE",
		  "pmarsceill/just-the-docs",
		  "sit-down-strike-count/sit-down-strike-count.github.io",
		  "yk-liu/yk-liu.github.io"
		],
		"count": 51,
		"사용자종류": null,
		"login": "BK-Choi",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-01-20 18:52:30.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "Baeyounri",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-19 05:20:11.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "BoKyeong-Kim/BDA",
		  "BoKyeong-Kim/BDA_LAB",
		  "BoKyeong-Kim/BoKyeong-Kim.github.io",
		  "BoKyeong-Kim/DB",
		  "BoKyeong-Kim/HOME",
		  "BoKyeong-Kim/HOME-PAGES",
		  "BoKyeong-Kim/HOMEPAGE",
		  "BoKyeong-Kim/Java",
		  "BoKyeong-Kim/Socket",
		  "BoKyeong-Kim/algorithm",
		  "BoKyeong-Kim/crawling",
		  "BoKyeong-Kim/finance_modeling",
		  "BoKyeong-Kim/fintech_",
		  "BoKyeong-Kim/test",
		  "OPAYA/DeepLearning_Paper_Implementation",
		  "OPAYA/Everything_TimeSeries",
		  "OPAYA/GoUarm",
		  "OPAYA/KAIR_Project",
		  "OPAYA/Kaggle_KR",
		  "OPAYA/PythonRobotics",
		  "OPAYA/Python_Algorithm",
		  "OPAYA/lets-do-gail",
		  "OPAYA/membership",
		  "OPAYA/pytorch-tutorial-1",
		  "PacktPublishing/Python-GUI-Programming-Cookbook-Second-Edition",
		  "RLOpensource/Relational_Deep_Reinforcement_Learning",
		  "aifrenz/membership",
		  "ankitsultana/accent",
		  "jupyter/notebook",
		  "kyg1552/DATS_RC_CAR",
		  "metatron-app/metatron-discovery",
		  "ndb796/Vegita",
		  "nlp2bok/fintech",
		  "nlp2bok/fintech_",
		  "thelehhman/plainwhite-jekyll"
		],
		"count": 224,
		"사용자종류": null,
		"login": "BoKyeong-Kim",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-05-01 03:26:26.000+0900"
	  },
	  {
		"meta": 2,
		"repos": [
		  "3epnm/drumjs",
		  "AntoineCheron/reactivewebserver",
		  "AssemblyScript/assemblyscript",
		  "ByeongGi/-DiretivesExample002",
		  "ByeongGi/CAPA001",
		  "ByeongGi/DiretivesExample001",
		  "ByeongGi/Gitcha-Gists",
		  "ByeongGi/TsNode",
		  "ByeongGi/TsNodeBatch",
		  "ByeongGi/analysis_d3-selection",
		  "ByeongGi/angularDoc",
		  "ByeongGi/bengis-ui",
		  "ByeongGi/byeonggi.github.io",
		  "ByeongGi/byeonggi.github.io.source",
		  "ByeongGi/changeDetectionExample",
		  "ByeongGi/changeDetectionExampleNgZone",
		  "ByeongGi/changeDetectionExampleOnPush",
		  "ByeongGi/changeDetectorRefExample",
		  "ByeongGi/coffice-order",
		  "ByeongGi/d3Example",
		  "ByeongGi/ie-webworker-gitpages",
		  "ByeongGi/ie-webworker-test",
		  "ByeongGi/ng-ionic",
		  "ByeongGi/pipeExample001",
		  "ByeongGi/rxjsExample",
		  "ByeongGi/todo-react",
		  "ByeongGi/webql",
		  "CarmenPopoviciu/protractor-styleguide",
		  "DefinitelyTyped/DefinitelyTyped",
		  "Functional-JavaScript/functional.es",
		  "Gitcha-Apatis-Team/Coin-Data",
		  "Gitcha-Apatis-Team/coin-dashboard-ui",
		  "Gitcha-Apatis-Team/coin-dashboard-ui-bootstrap",
		  "Gitcha-Apatis-Team/coin-data-collector",
		  "Gitcha-Apatis-Team/coni-dashboard-ui",
		  "Gitcha-Beginners/Gitcha-Gists",
		  "JonnyFox/websocket-node-express",
		  "LearningByExample/reactive-ms-example",
		  "Microsoft/TypeScript-Handbook",
		  "ReactiveX/rxjs",
		  "TypeScriptKR/TypeScript-Handbook",
		  "VividcodeIO/spring5-webflux-functional-starter",
		  "Zizzamia/perfume.js",
		  "abhishekkyd/protractor-html-reporter-2",
		  "akserg/ng2-dnd",
		  "alexreardon/css-box-model",
		  "angular-kr/angular",
		  "angular-kr/angular-kr-logo",
		  "angular-kr/angular-kr.github.io",
		  "angular-kr/angularkr-logo",
		  "angular/angular",
		  "angular/flex-layout",
		  "biggora/express-useragent",
		  "chromaui/learnstorybook.com",
		  "denoland/deno",
		  "emeeks/d3_in_action_2",
		  "f-act/wiki",
		  "facebook/jsx",
		  "felixrieseberg/electron-windows-notifications",
		  "ionic-team/capacitor",
		  "jgthms/bulma",
		  "jojoldu/springboot-webservice",
		  "kittykatattack/learningPixi",
		  "lord/slate",
		  "maljukan/typescript-node-rest-starter",
		  "marpple/partial.js",
		  "mattermost/mattermost-server",
		  "mattermost/mattermost-webapp",
		  "metafizzy/flickity",
		  "metatron-app/metatron-discovery",
		  "microsoft/vscode",
		  "minwan1/spring-security-oauth2-example",
		  "mixitconf/mixit",
		  "mout/mout",
		  "nestjs/nest",
		  "ng-bootstrap/ng-bootstrap",
		  "nhnent/fe.javascript",
		  "nigayo/2018-front-end-curriculum",
		  "pillarjs/path-to-regexp",
		  "reactjs/redux",
		  "rsirs/jasmine-custom-reporters",
		  "sdeleuze/spring-boot-kotlin-demo",
		  "shakyShane/json-ts",
		  "spring-petclinic/spring-petclinic-kotlin",
		  "spring-projects/spring-framework",
		  "storybooks/storybook",
		  "styled-components/polished",
		  "swimlane/ngx-charts",
		  "uriyang/fnjs_study_todo",
		  "valor-software/ngx-bootstrap",
		  "vmware/clarity",
		  "wonism/TIL",
		  "xieziyu/angular2-draggable",
		  "yui/yui2"
		],
		"count": 380,
		"사용자종류": null,
		"login": "ByeongGi",
		"type": [
		  "ForkEvent",
		  "WatchEvent"
		],
		"_time": "2018-01-01 09:42:15.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "ByeongjunCho/ByeongjunCho.github.io",
		  "ByeongjunCho/IppCreate",
		  "ByeongjunCho/MyProject1",
		  "ByeongjunCho/NaverAPI-telegram",
		  "ByeongjunCho/Python_ETC",
		  "ByeongjunCho/SSAFY_Python",
		  "ByeongjunCho/Solar_Monitoring_System",
		  "ByeongjunCho/TIL",
		  "ByeongjunCho/django-crud",
		  "ByeongjunCho/end_to_end",
		  "ByeongjunCho/first-django-project",
		  "ByeongjunCho/gittest",
		  "edutak/algorithms",
		  "metatron-app/metatron-discovery"
		],
		"count": 128,
		"사용자종류": null,
		"login": "ByeongjunCho",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-01-03 11:31:42.000+0900"
	  },
	  {
		"meta": 2,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 2,
		"사용자종류": null,
		"login": "CELINE-JEON",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-28 08:03:45.000+0900"
	  },
	  {
		"meta": 2,
		"repos": [
		  "CHAEUNPARK/-",
		  "CHAEUNPARK/AIDevelop_DeepDive1",
		  "CHAEUNPARK/AIDevelop_Python",
		  "CHAEUNPARK/AndroidTest",
		  "CHAEUNPARK/Engineering-Information-Processing",
		  "CHAEUNPARK/RPractice",
		  "CHAEUNPARK/SQLD",
		  "CHAEUNPARK/boardexample",
		  "CHAEUNPARK/ichshopping",
		  "CHAEUNPARK/springtest",
		  "Microsoft/vscode-mssql",
		  "PhilJay/MPAndroidChart",
		  "TheAlgorithms/Java",
		  "gilbutITbook/006958",
		  "metatron-app/metatron-discovery",
		  "phantasmicmeans/DaeHeeKim-Review",
		  "phantasmicmeans/back-end-developer-interview-questions",
		  "phantasmicmeans/junior-recruit-scheduler",
		  "prolificinteractive/material-calendarview"
		],
		"count": 115,
		"사용자종류": null,
		"login": "CHAEUNPARK",
		"type": [
		  "ForkEvent",
		  "WatchEvent"
		],
		"_time": "2018-08-18 19:52:30.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "CHOI0125/CHOI0125.io",
		  "CHOI0125/choi0125.github.com",
		  "CHOI0125/portfolio",
		  "CHOI0125/treejs_trial",
		  "metatron-app/metatron-discovery",
		  "mjung1798/AskforEwha"
		],
		"count": 32,
		"사용자종류": null,
		"login": "CHOI0125",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-02-17 06:05:51.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "CasterULT",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-17 03:55:41.000+0900"
	  },
	  {
		"meta": 3,
		"repos": [
		  "CgodL/JSBlog",
		  "CgodL/Project",
		  "CgodL/TIL",
		  "metatron-app/metatron-discovery",
		  "sohyona/chatterbox-express"
		],
		"count": 188,
		"사용자종류": null,
		"login": "CgodL",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-19 04:36:49.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "ChaHyunsung",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-31 06:54:01.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "Alamofire/Alamofire",
		  "ChangYeop-Yang/Activity-CapstoneDesign",
		  "ChangYeop-Yang/Activity-CapstoneDesignProject",
		  "ChangYeop-Yang/Activity-CapstoneDesignProject-1",
		  "ChangYeop-Yang/Activity-CapstoneDesignProject-2",
		  "ChangYeop-Yang/Activity-ConnectACE",
		  "ChangYeop-Yang/Android-Health1street",
		  "ChangYeop-Yang/Android-ILiveAlone",
		  "ChangYeop-Yang/Android-MyTravelNote",
		  "ChangYeop-Yang/Android-MylocationHow",
		  "ChangYeop-Yang/Android-Portfolio",
		  "ChangYeop-Yang/Android-ProjectR",
		  "ChangYeop-Yang/Android-TrackingBicycle",
		  "ChangYeop-Yang/CPL-20181-Team2",
		  "ChangYeop-Yang/ChangYeop-GitBlog.github.io",
		  "ChangYeop-Yang/ChangYeop-Yang.github.io",
		  "ChangYeop-Yang/Halve",
		  "ChangYeop-Yang/IOS-Health1street",
		  "ChangYeop-Yang/IOS-LazyHue",
		  "ChangYeop-Yang/IOS-OneDay",
		  "ChangYeop-Yang/IOS-RunToHealth",
		  "ChangYeop-Yang/Study-Algorithm",
		  "ChangYeop-Yang/Study-Android",
		  "ChangYeop-Yang/Study-C",
		  "ChangYeop-Yang/Study-ComputerScience",
		  "ChangYeop-Yang/Study-DataBase",
		  "ChangYeop-Yang/Study-DataScienceFoundation",
		  "ChangYeop-Yang/Study-DataStructure",
		  "ChangYeop-Yang/Study-FHIR",
		  "ChangYeop-Yang/Study-InformationRetrieval",
		  "ChangYeop-Yang/Study-Python",
		  "ChangYeop-Yang/Study-Swift",
		  "ChangYeop-Yang/Study-iOS",
		  "ChangYeop-Yang/Unix-SystemProgramming",
		  "ChangYeop-Yang/devportfolio",
		  "ChangYeop-Yang/iOS-OneDay",
		  "ChangYeop-Yang/iOS-RunToHealth",
		  "ClintJang/ios-swift-objc-questions-and-answers",
		  "Coldy24/2018_1_Web-Server_Programming_BoardGame",
		  "JeaSungLEE/iOSInterviewquestions",
		  "Ramotion/animated-tab-bar",
		  "RyanFitzgerald/devportfolio",
		  "SwiftKickMobile/SwiftMessages",
		  "TaylanTatli/Halve",
		  "agusmakmun/agusmakmun.github.io",
		  "airbnb/lottie-android",
		  "app-developers/top",
		  "apple/swift",
		  "dkhamsing/open-source-ios-apps",
		  "giftbott/iOSDevLinks",
		  "hyperoslo/Whisper",
		  "icanzilb/SwiftSpinner",
		  "jojoldu/junior-recruit-scheduler",
		  "kakao/kakao.github.io",
		  "krzyzanowskim/CryptoSwift",
		  "likedan/Awesome-CoreML-Models",
		  "metatron-app/metatron-discovery",
		  "raywenderlich/swift-algorithm-club",
		  "realm/SwiftLint",
		  "romandev/contributhon2018",
		  "torvalds/linux"
		],
		"count": 2102,
		"사용자종류": null,
		"login": "ChangYeop-Yang",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-03-01 11:22:38.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "Chaosland",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-17 02:26:55.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "Charlotteeeee",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-26 15:26:59.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "CheongsuLee/SinkDotCom",
		  "CheongsuLee/cheongsu.github.io",
		  "CheongsuLee/majorMatch",
		  "CheongsuLee/web1",
		  "hochae2018/Java-program-practice-2019",
		  "metatron-app/metatron-discovery"
		],
		"count": 13,
		"사용자종류": null,
		"login": "CheongsuLee",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-04-05 07:06:43.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "ChickenPaella/Panopticon",
		  "ChickenPaella/Sloot",
		  "ChickenPaella/Spring-Quick-Start",
		  "ChickenPaella/appetizer",
		  "ChickenPaella/goalgoru-app",
		  "ChickenPaella/swot",
		  "GESCC/danchu",
		  "JaeYeopHan/Interview_Question_for_Beginner",
		  "JetBrains/swot",
		  "antirez/redis",
		  "auth0/auth0-java",
		  "facebook/react",
		  "felixrieseberg/windows95",
		  "golang/go",
		  "gradle/gradle",
		  "hibernate/hibernate-orm",
		  "metatron-app/metatron-discovery",
		  "spring-projects/spring-framework",
		  "winterbe/streamjs",
		  "xetorthio/jedis"
		],
		"count": 98,
		"사용자종류": null,
		"login": "ChickenPaella",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-01-20 10:36:54.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "ChoiHanGeul/-",
		  "metatron-app/metatron-discovery"
		],
		"count": 7,
		"사용자종류": null,
		"login": "ChoiHanGeul",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-05-30 10:29:49.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "Choiyungmin",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-28 09:20:17.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "ChongYoon",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-19 05:37:46.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "ChungSoomin",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-19 03:08:35.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "2018cxx/hansori",
		  "CSID-DGU/2019-1-CECD4-MAKE_IT-3",
		  "CSID-DGU/Test",
		  "DDAMDOO/2018cxx",
		  "DDAMDOO/App",
		  "DDAMDOO/Bluetooth-pairing",
		  "DDAMDOO/algol",
		  "DDAMDOO/android_app_practice",
		  "DDAMDOO/ar",
		  "DDAMDOO/cxx",
		  "DDAMDOO/java_starter",
		  "DDAMDOO/mollo",
		  "DDAMDOO/realtime_query_app",
		  "DDAMDOO/template",
		  "devxoul/graygram-ios",
		  "makeitteam/AISpeaker",
		  "metatron-app/metatron-discovery"
		],
		"count": 146,
		"사용자종류": null,
		"login": "DDAMDOO",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-09-10 12:07:41.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "DaDaDaDang/AI-BigData-Study",
		  "DaDaDaDang/public",
		  "DaDaDaDang/sEpj",
		  "ai-starthon/AI_Starthon2019",
		  "dowonh/Dodam",
		  "metatron-app/metatron-discovery"
		],
		"count": 13,
		"사용자종류": null,
		"login": "DaDaDaDang",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-11-07 08:28:49.000+0900"
	  },
	  {
		"meta": 3,
		"repos": [
		  "AndrewCarterUK/pascal-voc-writer",
		  "Angel-ML/angel",
		  "DBWangGroupUNSW/nns_benchmark",
		  "DavidKo3/Capsule_network",
		  "DavidKo3/STFT_Feature_Extraction",
		  "DavidKo3/Sound_mixture_audiosegment",
		  "DavidKo3/image_feature_matching",
		  "DavidKo3/mctorch",
		  "DavidKo3/pyqt5_v1",
		  "DavidKo3/stock_prediction",
		  "Gurpreethgnis/CapsNet",
		  "JustGlowing/minisom",
		  "LCAV/pyroomacoustics",
		  "MagLoft/adcdownload",
		  "MathieuCarriere/perslay",
		  "MisaOgura/flashtorch",
		  "PacktPublishing/PyTorch-Deep-Learning-in-7-Days",
		  "RavenKyu/OpenTutorials_PyQt",
		  "SerpentAI/SerpentAI",
		  "ShichengChen/WaveUNet",
		  "SunnerLi/SVS-UNet-PyTorch",
		  "WebAssembly/design",
		  "XifengGuo/CapsNet-Keras",
		  "ZJULearning/nsg",
		  "ageitgey/face_recognition",
		  "amber0309/HSIC",
		  "ap229997/Variants_of_U-net",
		  "apache/incubator-mxnet",
		  "arXivTimes/arXivTimes",
		  "balzer82/FFT-Python",
		  "benedekrozemberczki/M-NMF",
		  "benedekrozemberczki/awesome-gradient-boosting-papers",
		  "bicv/LogGabor",
		  "bitnine-oss/agensgraph",
		  "boris-kz/CogAlg",
		  "brjathu/deepcaps",
		  "cedrickchee/capsule-net-pytorch",
		  "cedrickchee/pytorch-lite",
		  "cockroachdb/cockroach",
		  "craigmacartney/Wave-U-Net-For-Speech-Enhancement",
		  "creme-ml/creme",
		  "deepmind/multidim-image-augmentation",
		  "easezyc/deep-transfer-learning",
		  "edufonseca/icassp19",
		  "eriklindernoren/PyTorch-GAN",
		  "extreme-assistant/iccv2019",
		  "f90/Wave-U-Net",
		  "facebookresearch/pytorch_GAN_zoo",
		  "fengwang/minimal-capsule",
		  "fluent/fluent-bit",
		  "fmfn/BayesianOptimization",
		  "funcwj/conv-tasnet",
		  "funcwj/deep-clustering",
		  "google/web-audio-recognition",
		  "hadrienj/Preprocessing-for-deep-learning",
		  "higgsfield/Capsule-Network-Tutorial",
		  "hoya012/deep_learning_object_detection",
		  "jameslyons/python_speech_features",
		  "kaituoxu/Conv-TasNet",
		  "kamranahmedse/developer-roadmap",
		  "kanezaki/pytorch-rotationnet",
		  "kanezaki/rotationnet",
		  "keras-team/keras-applications",
		  "keunwoochoi/torchaudio-contrib",
		  "kimiyoung/ssl_bad_gan",
		  "ksanjeevan/crnn-audio-classification",
		  "ksanjeevan/torchparse",
		  "latentgnn/LatentGNN-V1-PyTorch",
		  "leftthomas/CapsuleLayer",
		  "leoxiaobin/deep-high-resolution-net.pytorch",
		  "libra/libra",
		  "librosa/librosa",
		  "lordet01/Tiny-DSOD",
		  "loretoparisi/CapsNet",
		  "lyxok1/Tiny-DSOD",
		  "maclab-kaist/DeepArt",
		  "maelfabien/Machine_Learning_Tutorials",
		  "metatron-app/metatron-discovery",
		  "numenta/nupic",
		  "numenta/nupic.torch",
		  "numenta/nupic.vision",
		  "onnx/models",
		  "pyqtgraph/pyqtgraph",
		  "pytorch/tnt",
		  "rasbt/deeplearning-models",
		  "renatopp/ratslam-python",
		  "rgeirhos/texture-vs-shape",
		  "rishabhmisra/Product-Catalog-Size-Recommendation-Framework",
		  "rusty1s/pytorch_sparse",
		  "sebastiani/IIC",
		  "sekwiatkowski/awesome-capsule-networks",
		  "sindresorhus/awesome",
		  "songdejia/EAST",
		  "ssrp/Multi-level-DCNet",
		  "thuml/Xlearn",
		  "trungngv/heroku-python-ml-example",
		  "trungngv/python-machine-learning-book-2nd-edition",
		  "utkuozbulak/pytorch-cnn-visualizations",
		  "xiph/rnnoise",
		  "zziz/pwc"
		],
		"count": 741,
		"사용자종류": null,
		"login": "DavidKo3",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-01-02 12:12:43.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "DayeonJung93/Practice_R",
		  "metatron-app/metatron-discovery"
		],
		"count": 3,
		"사용자종류": null,
		"login": "DayeonJung93",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-09-06 06:46:56.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "Delf-Lee/Coco-Chat",
		  "Delf-Lee/Daily-Programing",
		  "Delf-Lee/Devist",
		  "Delf-Lee/FOCUS",
		  "Delf-Lee/MiniProject",
		  "Delf-Lee/OAuth-tutorial",
		  "Delf-Lee/Snack-BE",
		  "Delf-Lee/aws-rds-article-keeper",
		  "Delf-Lee/blog-app",
		  "Delf-Lee/boostcourse-pjt-8-be",
		  "Delf-Lee/delf-lee.github.io",
		  "Delf-Lee/delf.github.io",
		  "Delf-Lee/effective-java",
		  "Delf-Lee/effective-java-3e-source-code",
		  "Delf-Lee/github-test",
		  "Delf-Lee/java-baseball",
		  "Delf-Lee/java-lotto",
		  "Delf-Lee/java-movie",
		  "Delf-Lee/java-racingcar",
		  "Delf-Lee/jwp-basic",
		  "Delf-Lee/my-first-blog",
		  "Delf-Lee/pacman",
		  "Delf-Lee/pre-devlist",
		  "Delf-Lee/spring-clould-workshop",
		  "Delf-Lee/spring-store",
		  "Delf-Lee/study-archive",
		  "Delf-Lee/team1-WannaOne",
		  "Delf-Lee/tech-interview",
		  "Delf-Lee/test",
		  "Delf-Lee/web-application-server",
		  "Do-Hee/algorithm-study",
		  "Do-Hee/tech-interview",
		  "Do-Hee/wwl",
		  "Integerous/goQuality-dev-contents",
		  "JaeYeopHan/Interview_Question_for_Beginner",
		  "MaximAbramchuck/awesome-interview-questions",
		  "NAVER-CAMPUS-HACKDAY/common",
		  "NESOY/Back-end-Developer-Interview-Questions",
		  "NESOY/Todolist",
		  "NESOY/nesoy.github.io",
		  "T-WWL/WWL",
		  "Team-Coper/Coco-Auth",
		  "Team-Coper/Coco-Chat",
		  "Team-Sprout/Clipcon-Client",
		  "WeareSoft/archive",
		  "WeareSoft/tech-interview",
		  "WeareSoft/wwl",
		  "biospin/BigBio",
		  "cheese10yun/spring-guide",
		  "cjh5414/Devist",
		  "doooyeon/baeminchan",
		  "doooyeon/baeminchan_cart",
		  "gmlwjd9405/news-blog-client",
		  "gmlwjd9405/todo-client",
		  "hexojs/hexo",
		  "jojoldu/junior-recruit-scheduler",
		  "kboard/kboard",
		  "mechero/spring-boot-testing-strategies",
		  "metatron-app/metatron-discovery",
		  "muabe/Propose",
		  "oaksong/developers-retrospective",
		  "rstoyanchev/spring-websocket-portfolio",
		  "slipp/web-application-server",
		  "snack-news/Snack-BE",
		  "spring-guides/gs-messaging-stomp-websocket",
		  "spring-projects/spring-boot",
		  "spring-projects/spring-framework",
		  "team-Devist/Devist",
		  "woowacourse/java-baseball",
		  "woowacourse/java-lotto",
		  "woowacourse/java-movie",
		  "woowacourse/java-racingcar",
		  "woowacourse/woowacourse-docs",
		  "wwh-techcamp-2018/team1-WannaOne"
		],
		"count": 1223,
		"사용자종류": null,
		"login": "Delf-Lee",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-01-11 11:07:11.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "Alex4386/NoGPKI",
		  "BasixKOR/awesome-activitypub",
		  "DevYourK/Changwon-LiveBus",
		  "DevYourK/KafuBot_discord",
		  "DevYourK/PHP-CityBus-Info",
		  "DevYourK/TwitterImage-bakje",
		  "DevYourK/YKTistorySkin",
		  "DevYourK/YTistorySkin",
		  "DevYourK/asK",
		  "DevYourK/devyourk.github.io",
		  "DevYourK/htmlTime",
		  "DevYourK/karaokeParser",
		  "DevYourK/wikiy_engine",
		  "DevYourK/yourk.github.io",
		  "GoogleChromeLabs/carlo",
		  "Hoto-Cocoa/CocoaCafeBot",
		  "Hoto-Cocoa/CocoaChatBot",
		  "JJoriping/KKuTu",
		  "JetBrains/swot",
		  "LaruYan/BlurSystemBarSample",
		  "Microsoft/MS-DOS",
		  "Seia-Soto/Ohys-Fanmade",
		  "Seia-Soto/invisibleHandshake",
		  "Su-Yong/KakaoImages",
		  "Su-Yong/KeyViewer",
		  "basis-vec/rinko",
		  "chrisbobbe/jekyll-theme-prologue",
		  "coreybutler/node-windows",
		  "deeppomf/DeepCreamPy",
		  "devHudi/bokmu-bot",
		  "dolsup/BanmalMode",
		  "dolsup/hyeongnya",
		  "dragonteros/unsuspected-hangeul",
		  "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
		  "electron/electron",
		  "femicoin/FEMICOIN-PROJECT",
		  "infinitered/nsfwjs",
		  "k4584587/docker_web_panel",
		  "metatron-app/metatron-discovery",
		  "nodejs/node",
		  "notkimwol/apperz-main",
		  "sokcuri/Json2CSV",
		  "sokcuri/TwimgSpeedPatch",
		  "sokcuri/pricone-stamp",
		  "sokcuri/twimg-mon",
		  "telk5093/TELKbot"
		],
		"count": 162,
		"사용자종류": null,
		"login": "DevYourK",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-05-14 11:02:22.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "Devaom/DevOps",
		  "Devaom/Devaom.github.io",
		  "Devaom/Fastcampus-web-deploy",
		  "Devaom/algorithms",
		  "Devaom/bongjaShark",
		  "Devaom/bongjafeed",
		  "Devaom/custom",
		  "Devaom/devops",
		  "Devaom/devops-ansible",
		  "Devaom/gproj",
		  "Devaom/helloworld",
		  "Devaom/inked-was",
		  "Devaom/inked-web",
		  "Devaom/kakaotalk_chatbot",
		  "Devaom/osteam",
		  "Devaom/website",
		  "brianmaierjr/long-haul",
		  "inked-lab/analysis-app",
		  "inked-lab/app-server",
		  "inked-lab/event-detect-app",
		  "inked-lab/nginx-conf",
		  "inked-lab/web-server",
		  "kubernetes/website",
		  "metatron-app/metatron-discovery",
		  "owen1025/Fastcampus-web-deploy",
		  "rohanchandra/type-theme",
		  "taki0112/StarGAN-Tensorflow"
		],
		"count": 197,
		"사용자종류": null,
		"login": "Devaom",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-03-14 09:57:03.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "55sketch/gsx2json",
		  "DevBluefrog/block-checker",
		  "DevBluefrog/devbluefrog.github.io",
		  "DevBluefrog/react-block-checker",
		  "Dilrong/2D_NoteShooting",
		  "Dilrong/AR_Find_Books",
		  "Dilrong/BeaconFinder",
		  "Dilrong/BookAgendaBot",
		  "Dilrong/Express_GuestBook",
		  "Dilrong/HelloJenkins",
		  "Dilrong/MemoryPalace",
		  "Dilrong/Node_TempbyZip",
		  "Dilrong/OfficeZombie",
		  "Dilrong/ProfileWithMongo",
		  "Dilrong/RN-OfficialsRestaurantMap",
		  "Dilrong/RN-memoryPalace",
		  "Dilrong/RN-public-restaurant-map",
		  "Dilrong/RN_Blog_Post",
		  "Dilrong/RN_Weather",
		  "Dilrong/Spoqa-Hackathon2019",
		  "Dilrong/TourOfHeroes",
		  "Dilrong/android-delicious-map",
		  "Dilrong/android-foodcast",
		  "Dilrong/anti-redux",
		  "Dilrong/bootstrap-iu",
		  "Dilrong/flask-inu-kakaobot",
		  "Dilrong/gatsby-gleans",
		  "Dilrong/gleans",
		  "Dilrong/gleans.me",
		  "Dilrong/kws-wegorego-app",
		  "Dilrong/moiveql",
		  "Dilrong/momonton",
		  "Dilrong/movieql-client",
		  "Dilrong/node-boilerplate",
		  "Dilrong/node-caudex",
		  "Dilrong/nomad-notes",
		  "Dilrong/nuber-server",
		  "Dilrong/projecteuler",
		  "Dilrong/public-delicious-map",
		  "Dilrong/public-restaurant-map",
		  "Dilrong/pwa-store",
		  "Dilrong/react-aha-pet",
		  "Dilrong/react-air_info",
		  "Dilrong/react-ajax-post",
		  "Dilrong/react-blog",
		  "Dilrong/react-bookshelves",
		  "Dilrong/react-counseling-here",
		  "Dilrong/react-country-list",
		  "Dilrong/react-delicious-map",
		  "Dilrong/react-foodquest-excel",
		  "Dilrong/react-movie_app",
		  "Dilrong/react-native-todolist",
		  "Dilrong/react-oneday_say",
		  "Dilrong/react-photo-feed",
		  "Dilrong/react-portfolio",
		  "Dilrong/react-standup",
		  "Dilrong/react-weather",
		  "Dilrong/rn-dogAir",
		  "Dilrong/rn-selfly",
		  "Dilrong/swift-foodtracker",
		  "Dilrong/ticTacToe",
		  "Dilrong/type-blockcahin",
		  "Vagr9K/gatsby-material-starter",
		  "airbnb/javascript",
		  "akiran/react-slick",
		  "atoami/react-native-navigation-redux-starter-kit",
		  "bluefrog-dev/bootstrap-morning-delight-event",
		  "bluefrog-dev/dining-crawler",
		  "bluefrog-dev/react-foodquest-excel",
		  "bluefrog-dev/react-weatly-event",
		  "bluefrog-io/PickyPromotion",
		  "bluefrog-io/android-foodcast",
		  "bluefrog-io/android-foodquset",
		  "bluefrog-io/flask-foodcast",
		  "bluefrog-io/frogMailer",
		  "bluefrog-io/node-foodquest",
		  "bluefrog-io/react-counseling-here",
		  "bluefrog-io/react-foodquest",
		  "bluefrog-io/react-foodquest-excel",
		  "goifproject/KWS",
		  "goifproject/kws-wegoreogo-app",
		  "jojoldu/junior-recruit-scheduler",
		  "junkies2019/junkiesFlow",
		  "junkies2019/react-junkiesflow",
		  "kairo96/and_node",
		  "kamranahmedse/developer-roadmap",
		  "kesuskim/Front-End-Checklist",
		  "madhavanmalolan/awesome-reactnative-ui",
		  "metatron-app/metatron-discovery",
		  "microsoft/Terminal",
		  "navermaps/marker-tools.js",
		  "qskeksq/BestFood",
		  "reduxjs/redux",
		  "serranoarevalo/kokoa-talk"
		],
		"count": 420,
		"사용자종류": null,
		"login": "Dilrong",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-01-04 03:54:54.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "Microsoft/Windows-tutorials-inputs-and-devices",
		  "metatron-app/metatron-discovery"
		],
		"count": 2,
		"사용자종류": null,
		"login": "DoYonKim",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-03-02 08:38:55.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "1ambda/terraform-all-in-one",
		  "AfterShip/challenge",
		  "DannyKang/OKEwithWercker",
		  "DannyKang/twitter-feed-oke",
		  "Dongjinmedia/Bigpoint",
		  "Dongjinmedia/RIPS",
		  "Dongjinmedia/SRE",
		  "Dongjinmedia/aftership",
		  "Dongjinmedia/bonial",
		  "Dongjinmedia/holidaypirates",
		  "Dongjinmedia/rakuten",
		  "Dongjinmedia/twitter-feed-oke",
		  "Durgaprasad-Nagarkatte/Simple-Flask-Shopping-Cart",
		  "ErnstHaagsman/ansible-flask",
		  "FJplant/freenas-resume-replication",
		  "ONLYOFFICE/DesktopEditors",
		  "TheOpenCloudEngine/uEngine-cloud",
		  "ansible/ansible-examples",
		  "ansible/awx",
		  "aranciaga/blackpearl",
		  "code-post/ariana_dashboard",
		  "hibou-io/odoo-newrelic",
		  "jojoldu/junior-recruit-scheduler",
		  "macports/macports-base",
		  "metatron-app/metatron-discovery",
		  "mybatis/jpetstore-6",
		  "rampart81/terraform-modules",
		  "torvalds/linux",
		  "uglide/RedisDesktopManager"
		],
		"count": 272,
		"사용자종류": null,
		"login": "Dongjinmedia",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-01-21 11:41:32.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "DongsikLim/cicd",
		  "DongsikLim/pcf_lab",
		  "DongsikLim/springbox-config-repo",
		  "hwshin16/springbox-config-repo",
		  "metatron-app/metatron-discovery"
		],
		"count": 7,
		"사용자종류": null,
		"login": "DongsikLim",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-01-19 07:19:19.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "Dongwook21",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-17 04:52:36.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "Dotols/201424519",
		  "Dotols/Mademoiselle",
		  "metatron-app/metatron-discovery",
		  "pnu-003-team4/GodOfDatabase",
		  "pusanselab/lgwork_backend",
		  "pusanselab/lgwork_frontend"
		],
		"count": 49,
		"사용자종류": null,
		"login": "Dotols",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-01-22 07:32:07.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery",
		  "thetarkus/WebMCam"
		],
		"count": 2,
		"사용자종류": null,
		"login": "Dozen7",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-04-22 05:24:52.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "EBvi/dandy",
		  "EBvi/dday",
		  "EBvi/dev-matrix",
		  "EBvi/doc",
		  "metafizzy/zdog",
		  "metatron-app/metatron-discovery",
		  "yeun/open-color",
		  "you-dont-need/You-Dont-Need-Momentjs",
		  "zxqfl/TabNine"
		],
		"count": 10,
		"사용자종류": null,
		"login": "EBvi",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-01-23 07:33:33.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "ByeongjunCho/end_to_end",
		  "EHwooKim/Algorithms",
		  "EHwooKim/EHwooKim.github.io",
		  "EHwooKim/Start_camp",
		  "EHwooKim/TIL",
		  "EHwooKim/crud-django-project",
		  "EHwooKim/first-django-project",
		  "EHwooKim/git_test",
		  "EHwooKim/telegram",
		  "edugieun/TIL_gieun",
		  "metatron-app/metatron-discovery"
		],
		"count": 126,
		"사용자종류": null,
		"login": "EHwooKim",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-09 01:05:42.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "EUNHAGYEONG/C_study",
		  "EUNHAGYEONG/ChattBott",
		  "EUNHAGYEONG/Data",
		  "EUNHAGYEONG/Rdata",
		  "EUNHAGYEONG/eh_chatbott",
		  "metatron-app/metatron-discovery",
		  "minsuk-heo/pandas"
		],
		"count": 138,
		"사용자종류": null,
		"login": "EUNHAGYEONG",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-09-28 09:13:02.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "EXPYH/algorithm_c",
		  "EXPYH/expyh.github.io",
		  "EXPYH/frienting-1",
		  "EXPYH/maybePortfolio",
		  "EhyunLee/frienting",
		  "EhyunLee/frienting_",
		  "Jpub/Linux_for_Everyone",
		  "hwkim94/hwkim94.github.io",
		  "metatron-app/metatron-discovery",
		  "mortdeus/legacy-cc"
		],
		"count": 48,
		"사용자종류": null,
		"login": "EXPYH",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-02-25 06:43:22.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "Trenbe/neo-trenbe-procedure",
		  "metatron-app/metatron-discovery"
		],
		"count": 2,
		"사용자종류": null,
		"login": "EdgarJLee",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-05-16 21:08:28.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "0voice/interview_internal_reference",
		  "AlbertHG/Machine-Learning-Yearning-Chinese-ver",
		  "ApolloAuto/apollo",
		  "BrambleXu/pydata-notebook",
		  "CodeTips/BaiduNetdiskPlugin-macOS",
		  "CorentinJ/Real-Time-Voice-Cloning",
		  "CyC2018/CS-Notes",
		  "DSKSD/DeepNLP-models-Pytorch",
		  "Dod-o/Statistical-Learning-Method_Code",
		  "Edwardong/CS162_PA1",
		  "Edwardong/CS165B_HW1",
		  "Edwardong/CS174A-ATM",
		  "Edwardong/Coursera-ML-AndrewNg-Notes",
		  "Edwardong/HSA",
		  "Edwardong/ML_Related_Work",
		  "Edwardong/cs162-tutorials",
		  "Edwardong/ucsb-cs56-gaochoalarm",
		  "Edwardong/ucsb-cs56-gauchoalarm",
		  "FudanNLP/nlp-beginner",
		  "Halfish/machine-learning-reference",
		  "LiuXingMing/SinaSpider",
		  "LookCos/hotspot-online",
		  "MisterBooo/LeetCodeAnimation",
		  "OUCMachineLearning/OUCML",
		  "PapyElGringo/material-shell",
		  "RajibTheKing/HSA",
		  "Snailclimb/JavaGuide",
		  "SwiftOldDriver/SwiftMarch",
		  "Tencent/bk-ci",
		  "TobiasLee/Chinese-Hip-pop-Generation",
		  "TobiasLee/Text-Classification",
		  "Vincedream/NodeMail",
		  "ZacBi/CS224n-2019-solutions",
		  "alibaba/p3c",
		  "apache/spark",
		  "apachecn/AiLearning",
		  "apachecn/ai-roadmap",
		  "apachecn/impatient-js-zh",
		  "apachecn/kaggle",
		  "apachecn/math",
		  "apachecn/ml-mastery-zh",
		  "asweigart/pyautogui",
		  "b3log/solo",
		  "bilibili/kratos",
		  "careercup/CtCI-6th-Edition",
		  "careercup/CtCI-6th-Edition-Python",
		  "cdr/sshcode",
		  "chai2010/advanced-go-programming-book",
		  "chai2010/go2-book",
		  "chrislgarry/Apollo-11",
		  "ctripcorp/apollo",
		  "datawhalechina/pumpkin-book",
		  "drduh/macOS-Security-and-Privacy-Guide",
		  "fastai/course-nlp",
		  "fchollet/deep-learning-with-python-notebooks",
		  "feixiao/Distributed-Systems",
		  "fengdu78/Coursera-ML-AndrewNg-Notes",
		  "fengdu78/Data-Science-Notes",
		  "fengdu78/lihang-code",
		  "fighting41love/funNLP",
		  "golang-china/gopl-zh",
		  "golang/groupcache",
		  "gto76/python-cheatsheet",
		  "guodongxiaren/README",
		  "hding1/NoteHub-Android",
		  "iina/iina",
		  "jackfrued/Python-100-Days",
		  "jdneo/vscode-leetcode",
		  "kelseyhightower/nocode",
		  "lenve/vhr",
		  "lib-pku/libpku",
		  "liuhuanyong/ComplexEventExtraction",
		  "mbinary/USTC-CS-Courses-Resource",
		  "mbinary/algorithm-in-python",
		  "metatron-app/metatron-discovery",
		  "microsoft/ai-edu",
		  "microsoft/vscode-dev-containers",
		  "niemand-sec/AntiCheat-Testing-Framework",
		  "nsoojin/coursera-ml-py",
		  "open-deepnude/open-deepnude",
		  "peterq/pan-light",
		  "pllab/CS162-regex",
		  "pllab/cs162-tutorials",
		  "polaris1119/The-Golang-Standard-Library-by-Example",
		  "rasbt/deeplearning-models",
		  "scutan90/DeepLearning-500-questions",
		  "sfyc23/EverydayWechat",
		  "sherlock-project/sherlock",
		  "switchablenorms/DeepFashion2",
		  "trekhleb/homemade-machine-learning",
		  "ucsb-cs56-m18/LECTURE_08.26",
		  "ucsb-cs56-webapps/ucsb-cs56-gaochoalarm",
		  "ucsb-cs56-webapps/ucsb-cs56-gauchoalarm",
		  "waylau/spring-boot-enterprise-application-development",
		  "wilsonyin123/geekbangpython",
		  "xiaolai/regular-investing-in-box",
		  "xkcoding/spring-boot-demo",
		  "xlzd/img2html",
		  "yunjey/pytorch-tutorial",
		  "zhaoolee/ChineseBQB"
		],
		"count": 216,
		"사용자종류": null,
		"login": "Edwardong",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-01-28 01:03:42.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "Eojin1178",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-18 06:10:46.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "Erik-Park/Erik-Park.github.io",
		  "Erik-Park/coupon",
		  "Erik-Park/ddd-start",
		  "Erik-Park/erik-park",
		  "Erik-Park/erik-park.github.io",
		  "Erik-Park/heaven",
		  "Erik-Park/https-erik-park.github.io",
		  "Erik-Park/myBoard",
		  "Erik-Park/pybot",
		  "Erik-Park/springBoard",
		  "Erik-Park/studySpring",
		  "Erik-Park/thecontact",
		  "Erik-Park/tutorial_SB",
		  "bladebone/boardboot",
		  "expert0226/oopinspring",
		  "madvirus/ddd-start",
		  "metatron-app/metatron-discovery",
		  "spring-projects/spring-petclinic",
		  "wikibook/advanced-android-book"
		],
		"count": 105,
		"사용자종류": null,
		"login": "Erik-Park",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-01-18 17:11:17.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "EthanShin/CardShare",
		  "EthanShin/EthanShin.github.io",
		  "EthanShin/Hackerrank",
		  "EthanShin/Kotlin",
		  "EthanShin/PpuingPpuing",
		  "EthanShin/SmartClass",
		  "EthanShin/TIL",
		  "EthanShin/hackerrank-1",
		  "EthanShin/hanbang-weather",
		  "EthanShin/mobile-tracker",
		  "EthanShin/new",
		  "EthanShin/weather-pollution",
		  "VintageAppMaker/CardShare",
		  "a1ahn/mobile-tracker",
		  "metatron-app/metatron-discovery",
		  "ulgoon/hackerrank",
		  "ulgoon/hanbang-weather"
		],
		"count": 1041,
		"사용자종류": null,
		"login": "EthanShin",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-01-03 13:12:58.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "EuiJaeKim/Artificial_Intelligence",
		  "EuiJaeKim/Programing",
		  "EuiJaeKim/Programming",
		  "EuiJaeKim/Yonsei",
		  "ai-starthon/AI_Starthon2019",
		  "artikcloud/artikcloud-lwm2m-c",
		  "aspose-slides/Aspose.Slides-for-C",
		  "metatron-app/metatron-discovery"
		],
		"count": 79,
		"사용자종류": null,
		"login": "EuiJaeKim",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-05-02 02:29:05.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "FrancisLee1025",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-18 05:00:22.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "Gangyouna",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-28 08:47:07.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "GayoungHan",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-18 01:56:12.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "Giyounsook",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-28 09:12:29.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "Glorywhale/TMS_Manager",
		  "Glorywhale/kotlin-android",
		  "Glorywhale/webtms",
		  "metatron-app/metatron-discovery",
		  "soongon/kotlin-android"
		],
		"count": 7,
		"사용자종류": null,
		"login": "Glorywhale",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-01-25 08:02:01.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "AdguardTeam/AdGuardHome",
		  "BayesWitnesses/m2cgen",
		  "ChrisKnott/Algojammer",
		  "CorentinJ/Real-Time-Voice-Cloning",
		  "GoogilyBoogily/dockerfiles",
		  "GoogilyBoogily/unraid-docker-templates",
		  "Hellowlol/bw_plex",
		  "Igglybuff/awesome-piracy",
		  "InterviewMap/InterviewMap",
		  "Ji4n1ng/OpenInTerminal",
		  "LisaDziuba/Awesome-Design-Tools",
		  "Microsoft/vscode-remote-release",
		  "NVIDIAGameWorks/PhysX-3.4",
		  "Raathigesh/fabulous",
		  "Tayx94/graphy",
		  "UKHomeOffice/repo-security-scanner",
		  "ValveSoftware/IndexHardware",
		  "adoyle-h/lobash",
		  "akveo/eva-icons",
		  "amborle/featmap",
		  "ant-design/ant-design",
		  "antonmedv/fx",
		  "apache/skywalking",
		  "bloc97/Anime4K",
		  "bryphe/revery",
		  "bvaughn/progress-estimator",
		  "chrislgarry/Apollo-11",
		  "chubin/cheat.sh",
		  "codercom/code-server",
		  "cvarta/deluge-extractor",
		  "davebs/AgileLite",
		  "daybrush/moveable",
		  "deeppomf/DeepCreamPy",
		  "developit/htm",
		  "dreamingechoes/awesome-mental-health",
		  "duke7553/files-uwp",
		  "ecumene-software/rust-sloth",
		  "ehmicky/nve",
		  "electron/fiddle",
		  "felixrieseberg/windows95",
		  "github/dmca",
		  "github/glb-director",
		  "github/orchestrator",
		  "github/semantic",
		  "google/data-transfer-project",
		  "google/filament",
		  "google/robotstxt",
		  "grafana/loki",
		  "guysoft/FullPageOS",
		  "hanford/trends",
		  "hugetiny/negibox",
		  "ian13456/mc.js",
		  "jacobwgillespie/plex-sync",
		  "jellyfin/jellyfin",
		  "jesseduffield/lazydocker",
		  "keenanwoodall/Deform",
		  "koalaman/shellcheck",
		  "kubernetes/minikube",
		  "lettier/3d-game-shaders-for-beginners",
		  "liamg/tml",
		  "localstack/localstack",
		  "m3db/m3",
		  "marcan/takeover.sh",
		  "metatron-app/metatron-discovery",
		  "mholt/timeliner",
		  "microsoft/PowerToys",
		  "microsoft/Terminal",
		  "microsoft/just",
		  "muesli/gitomatic",
		  "nasa-jpl/open-source-rover",
		  "nathan/pax",
		  "niieani/bash-oo-framework",
		  "nodegui/nodegui",
		  "npm/tink",
		  "oclif/oclif",
		  "open-source-ideas/open-source-ideas",
		  "openvenues/libpostal",
		  "ovh/cds",
		  "pardeike/Harmony",
		  "pathephone/pathephone-desktop",
		  "paubric/awesome-doesnotexist",
		  "reactiveops/polaris",
		  "robb0wen/synthwave-vscode",
		  "samuelmaddock/metastream",
		  "scipr-lab/zexe",
		  "sdispater/poetry",
		  "slothking-online/graphql-editor",
		  "sqshq/sampler",
		  "tajo/react-movable",
		  "thepracticaldev/dev.to",
		  "timberio/vector",
		  "trimstray/the-book-of-secret-knowledge",
		  "uber/kraken",
		  "ulid/spec",
		  "valeriansaliou/sonic",
		  "vmware/octant",
		  "wagoodman/dive",
		  "xraxra/IMP",
		  "zadam/trilium",
		  "zziz/pwc"
		],
		"count": 198,
		"사용자종류": null,
		"login": "GoogilyBoogily",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-01-04 23:41:26.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "Gowoonchoi",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-26 01:37:14.000+0900"
	  },
	  {
		"meta": 2,
		"repos": [
		  "A-l-y-l-e/Alyle-UI",
		  "Bios-Marcel/cordless",
		  "Bogdanp/hebi",
		  "DanielDe/org-web",
		  "ES-Community/nsecure",
		  "EvanBacon/AWESOME-REACT-NATIVE-WEB",
		  "IsraelAdura/go-postgres-jwt-react-starter",
		  "KriNeko/marshalling-binary-struct-js",
		  "Marak/say.js",
		  "MichMich/MagicMirror",
		  "MozillaReality/immersive-custom-elements",
		  "Roblouisck/mysaves.app",
		  "Y2Z/monolith",
		  "Zackhardtoname/internships",
		  "alexmacarthur/typeit",
		  "aloisdeniel/flutter_shared_ui_poc",
		  "angular/components",
		  "axios/axios",
		  "benlesh/rxjs-web-animation",
		  "bestony/OpenSourceMenu",
		  "bmcmahen/react-gesture-stack",
		  "bvaughn/react-devtools-tutorial",
		  "celo-org/celo-monorepo",
		  "chrislgarry/Apollo-11",
		  "christianvoigt/argdown",
		  "cutenode/delice",
		  "dabit3/conference-app-in-a-box",
		  "date-fns/date-fns",
		  "daybrush/moveable",
		  "drakkan/sftpgo",
		  "egoist/vue-to-react",
		  "eko/monday",
		  "facebook/hermes",
		  "feross/chrome-dns",
		  "feross/feross",
		  "figma/plugin-samples",
		  "framer/motion",
		  "fruitcake/laravel-telescope-toolbar",
		  "givanz/VvvebJs",
		  "goldbergyoni/nodebestpractices",
		  "graphql-editor/graphql-zeus",
		  "graphql/graphql-js",
		  "hayderux/electron-quick-start-flutter",
		  "hyperswarm/hyperswarm",
		  "i0natan/nodebestpractices",
		  "iampawan/GDG-DevFest-App",
		  "ian13456/mc.js",
		  "ianstormtaylor/slate",
		  "immerjs/immer",
		  "immutable-js/immutable-js",
		  "jgraph/drawio",
		  "jlengstorf/gatsby-theme-jam-example",
		  "johnfactotum/foliate",
		  "juliasilge/supervised-ML-case-studies-course",
		  "kapunahelewong/git-playground",
		  "ksky521/nodeppt",
		  "libra/website",
		  "lightningminers/awesome-indie",
		  "lukeed/throttles",
		  "mafintosh/hyperssh",
		  "maierfelix/tiny-rtx",
		  "manfredsteyer/angular-oauth2-oidc",
		  "mapbox/martini",
		  "metatron-app/metatron-discovery",
		  "microsoft/WebTemplateStudio",
		  "microsoft/just",
		  "minimaxir/mtg-gpt-2-cloud-run",
		  "mrdoob/three.js",
		  "mysigmail/html-email-templates",
		  "narative/gatsby-theme-novela",
		  "ng-packagr/ng-packagr",
		  "nodegui/react-nodegui",
		  "odoo/odoo",
		  "oliver-moran/jimp",
		  "paulhodel/jexcel",
		  "peng666/react-awesome-player",
		  "quii/learn-go-with-tests",
		  "radiegtya/nodejs-graphql-microservices",
		  "ronomon/zip",
		  "royriojas/flat-cache",
		  "ryanmcdermott/clean-code-javascript",
		  "sandoche/Detoxify-app",
		  "schollz/hostyoself",
		  "scitbiz/flutter_pokedex",
		  "serverless/components",
		  "symfony/error-catcher",
		  "symfony/error-handler",
		  "teambit/bit",
		  "themesberg/windows-95-ui-kit",
		  "timqian/chart.xkcd",
		  "trimstray/nginx-admins-handbook",
		  "vadimdemedes/reconciled",
		  "vintasoftware/eslint-config-vinta",
		  "vuejs/vue-cli",
		  "vuejs/vue-devtools",
		  "vuejs/vue-function-api",
		  "vuejs/vue-router",
		  "vuejs/vuepress",
		  "vuejs/vuex",
		  "yangshun/front-end-interview-handbook"
		],
		"count": 276,
		"사용자종류": null,
		"login": "Grenadator",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-02-01 11:22:12.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "GunHeeKim127",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-18 07:20:44.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "GyuilHwang/mapproject",
		  "GyuilHwang/my-first-blog",
		  "GyuilHwang/my-first-blog2",
		  "metatron-app/metatron-discovery"
		],
		"count": 9,
		"사용자종류": null,
		"login": "GyuilHwang",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-17 08:16:08.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "H-Noah/H-Noah",
		  "H-Noah/H-Noah.github.io",
		  "H-Noah/git-flow-study",
		  "H-Noah/our-home",
		  "H-Noah/prography-FE-homework",
		  "H-Noah/retrospective-diary",
		  "H-Noah/vuetify-for-ref",
		  "Seolhun/retrospective-diary",
		  "blueStragglr/myref-front",
		  "gmlwjd9405/gmlwjd9405.github.io",
		  "junhobaik/junhobaik.github.io",
		  "metatron-app/metatron-discovery",
		  "mmistakes/minimal-mistakes",
		  "prography/our-home-refrigerator",
		  "prography/song-request-app",
		  "prography/web-frontend",
		  "sthkindacrazy/prography_sample"
		],
		"count": 150,
		"사용자종류": null,
		"login": "H-Noah",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-10-11 05:35:49.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "HYUNNY99",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-25 14:07:53.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "0wczar/airframe-react",
		  "BurntSushi/xsv",
		  "ColorlibHQ/gentelella",
		  "Dalimil/Web-Design-Pirate",
		  "DrQueue/drqueue",
		  "FrissAnalytics/shinyJsTutorials",
		  "Mailtrain-org/mailtrain",
		  "MarkEdmondson1234/gentelellaShiny",
		  "Unidata/UDUNITS-2",
		  "WinVector/rquery",
		  "Y2Z/monolith",
		  "amejiarosario/dsa.js-data-structures-algorithms-javascript",
		  "ananas-analytics/ananas-desktop",
		  "andkret/Cookbook",
		  "ankane/jetpack",
		  "anthonynorth/rscodeio",
		  "apache/arrow",
		  "apache/calcite",
		  "apache/carbondata",
		  "apache/incubator-druid",
		  "apache/incubator-pinot",
		  "apache/netbeans",
		  "apache/tinkerpop",
		  "apache/zeppelin",
		  "cdr/code-server",
		  "chris-torrence/wavelets",
		  "christophM/interpretable-ml-book",
		  "christophergandrud/networkD3",
		  "daattali/colourpicker",
		  "daattali/shinyalert",
		  "daattali/timevis",
		  "dangom/org-thesis",
		  "danklammer/bytesize-icons",
		  "data-cleaning/validate",
		  "dm3ll3n/ShinyStudio",
		  "dtinth/ttycast",
		  "edent/SuperTinyIcons",
		  "egenn/rtemis",
		  "eisman/neo4jd3",
		  "evolus/pencil",
		  "feathericons/feather",
		  "gadenbuie/tidyexplain",
		  "gilbarbara/logos",
		  "google/open-location-code",
		  "google/or-tools",
		  "hak5darren/USB-Rubber-Ducky",
		  "hemanta212/blogger-cli",
		  "huyingjie/Awesome-shiny-apps-for-statistics",
		  "iagox86/dnscat2",
		  "inbo/inborutils",
		  "klokantech/tileserver-gl",
		  "knadh/listmonk",
		  "lagodiuk/decision-tree-js",
		  "leaflet-extras/leaflet-providers",
		  "liftbridge-io/liftbridge",
		  "mailgun/gubernator",
		  "mapbox/awesome-vector-tiles",
		  "maxmcd/webtty",
		  "meetalva/alva",
		  "metatron-app/metatron-discovery",
		  "mickael-kerjean/filestash",
		  "microweber/microweber",
		  "mkhairi/undraw",
		  "mtrencseni/rxe",
		  "nanxstats/awesome-shiny-extensions",
		  "nodemailer/wildduck",
		  "notlmn/awesome-icons",
		  "open-meta/om_skeleton",
		  "openmaptiles/openmaptiles",
		  "ory/hydra",
		  "phpList/phplist3",
		  "pixijs/pixi.js",
		  "r-lib/callr",
		  "r0f1/datascience",
		  "radiant-rstats/radiant",
		  "renkun-ken/formattable",
		  "rstudio/bookdown",
		  "rstudio/crosstalk",
		  "rstudio/gt",
		  "rstudio/pool",
		  "rstudio/renv",
		  "s0lly/Raytracer-In-Excel",
		  "seemoo-lab/opendrop",
		  "snovvcrash/usbrip",
		  "statnet/ndtv",
		  "streamhut/streamhut",
		  "strengejacke/ggeffects",
		  "superdesk/superdesk",
		  "svg/svgo",
		  "systemed/tilemaker",
		  "tangrams/icons",
		  "themesberg/pixel-lite-bootstrap-4-ui-kit",
		  "thomasp85/ggraph",
		  "tilezen/joerd",
		  "tilezen/vector-datasource",
		  "tmate-io/tmate",
		  "trestletech/shinyAce",
		  "ua-snap/shiny-apps",
		  "vitorbaptista/shellshare",
		  "yarrick/iodine"
		],
		"count": 305,
		"사용자종류": null,
		"login": "HalfEatenPie",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-01-10 21:38:43.000+0900"
	  },
	  {
		"meta": 2,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 2,
		"사용자종류": null,
		"login": "HanJeongok",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-29 03:57:36.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "Hanbyeol-Yoo/Hackerrank_Data_Structures",
		  "metatron-app/metatron-discovery"
		],
		"count": 2,
		"사용자종류": null,
		"login": "Hanbyeol-Yoo",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-05-30 23:10:02.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "HanoChoi/DropTheGenie",
		  "HanoChoi/StudyHTML",
		  "HanoChoi/web",
		  "HanoChoi/wp",
		  "group-for-project/HanoTest1",
		  "group-for-project/WebStudy1",
		  "metatron-app/metatron-discovery"
		],
		"count": 47,
		"사용자종류": null,
		"login": "HanoChoi",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-02-20 06:55:56.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "HasunJung/hasunjung.github.io",
		  "HasunJung/spring-data-redis-example",
		  "metatron-app/metatron-discovery",
		  "webrtc/apprtc"
		],
		"count": 11,
		"사용자종류": null,
		"login": "HasunJung",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-05-17 07:35:32.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery",
		  "myevertime/2018-Big-data-Contest",
		  "myevertime/LPOINT-BigData-Analysis"
		],
		"count": 3,
		"사용자종류": null,
		"login": "Heemoonn",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-01-17 08:01:02.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "Henryshin/HenryShin.github.io",
		  "Henryshin/blog",
		  "Henryshin/djangoproject",
		  "Henryshin/github.io",
		  "Henryshin/klplmfp.github.io",
		  "deeplearningzerotoall/PyTorch",
		  "hufslikelion7/Henry",
		  "hufslikelion7/goob",
		  "hufslikelion7/jongman",
		  "hunkim/DeepLearningZeroToAll",
		  "metatron-app/metatron-discovery"
		],
		"count": 21,
		"사용자종류": null,
		"login": "Henryshin",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-03-27 12:39:38.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "ClintJang/awesome-swift-korean-lecture",
		  "ClintJang/ios-swift-objc-questions-and-answers",
		  "Developer-Leby/PodsLibrary",
		  "Heo-Seoyeong/Backjoon",
		  "Heo-Seoyeong/Flutter_Example",
		  "Heo-Seoyeong/JandiBot",
		  "Heo-Seoyeong/JandiLunch",
		  "Heo-Seoyeong/QRReader_Swift",
		  "Heo-Seoyeong/RESUME",
		  "Heo-Seoyeong/SYSDK",
		  "Heo-Seoyeong/Study-SwiftBasic-Yagom",
		  "Heo-Seoyeong/Study_RxSwift",
		  "Heo-Seoyeong/Study_Swift4",
		  "Heo-Seoyeong/Study_SwiftUI",
		  "Heo-Seoyeong/Study_Swift_Apps",
		  "Heo-Seoyeong/Study_Swift_Bagic",
		  "Heo-Seoyeong/SwiftUI_Demo",
		  "Heo-Seoyeong/SwiftUI_Tutorial",
		  "Heo-Seoyeong/Swift_Template_WebView",
		  "Heo-Seoyeong/UNOSYSDK",
		  "Heo-Seoyeong/heo-seoyeong.github.io",
		  "Heo-Seoyeong/iOS_AUSG_Amplify",
		  "Heo-Seoyeong/iOS_Boostcourse_PJT1_MusicPlayer",
		  "Heo-Seoyeong/iOS_boostcamp_3",
		  "Heo-Seoyeong/resume",
		  "Heo-Seoyeong/sorting_iOS",
		  "JaeYeopHan/Interview_Question_for_Beginner",
		  "Juanpe/About-SwiftUI",
		  "Kofktu/KUIKeyboard",
		  "RxSwiftCommunity/RxFlow",
		  "Swinject/Swinject",
		  "TextureGroup/Texture",
		  "andreamazz/SubtleVolume",
		  "apple/swift-internals",
		  "apple/turicreate",
		  "bencentra/centrarium",
		  "boostcamp-connect/boostcamp_3_iOS",
		  "cruisediary/DeviceLayout",
		  "cruisediary/Gradients",
		  "dev-hjJoo/Study-SwiftBasic-Yagom",
		  "dev-hjJoo/Study-makeApp-iOS",
		  "dev-hjJoo/Swift_Basic_Yagom",
		  "devxoul/RxTodo",
		  "devxoul/SwiftUITodo",
		  "fastlane/fastlane",
		  "fimuxd/RxSwift",
		  "flutter/samples",
		  "freshOS/KeyboardLayoutGuide",
		  "h5bp/Front-end-Developer-Interview-Questions",
		  "huri000/SwiftEntryKit",
		  "iamcho2/AUSG-amplify-seminar",
		  "ioscreator/ioscreator",
		  "jojoldu/junior-recruit-scheduler",
		  "jojoldu/resume",
		  "justjavac/free-programming-books-zh_CN",
		  "kawoou/Deli",
		  "kawoou/DeliTodo",
		  "kickstarter/ios-oss",
		  "makomori/Sharaku",
		  "metatron-app/metatron-discovery",
		  "seoyoungk/myApps",
		  "seoyoungk/swift_basic",
		  "seriLucute/RESUME",
		  "smt/resume",
		  "soapyigu/Swift-30-Projects",
		  "stencilproject/Stencil",
		  "taewan0530/DeviceFontSize",
		  "tristanhimmelman/ObjectMapper",
		  "vbmania/RxValidator",
		  "vsouza/awesome-ios",
		  "yahoojapan/UICollectionViewSplitLayout",
		  "yjs03057/33-js-concepts",
		  "yoonhg84/CPIndentLabel",
		  "yoonhg84/ios-qna",
		  "yoonhg84/resume",
		  "ytakzk/Fusuma"
		],
		"count": 246,
		"사용자종류": null,
		"login": "Heo-Seoyeong",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-01-12 14:31:37.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "HoJungLee/2018HallymC-Task",
		  "HoJungLee/2018HallymCTask",
		  "HoJungLee/DataAnalysis",
		  "HoJungLee/HallymDataStructures",
		  "HoJungLee/MedicalStatics",
		  "HoJungLee/Parallel_Programming_2018_Fall",
		  "HoJungLee/cattleIdentification",
		  "HoJungLee/nothing",
		  "HoJungLee/studyDataBase",
		  "bigdata-3-group/korea-3",
		  "jeonggunlee/Parallel_Programming_2018_Fall",
		  "metatron-app/metatron-discovery"
		],
		"count": 124,
		"사용자종류": null,
		"login": "HoJungLee",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-10-16 04:45:53.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "Hogaeng/IonicApp",
		  "Sayaten/OneDayOneStudy",
		  "metatron-app/metatron-discovery",
		  "shkim5164/algorithm"
		],
		"count": 12,
		"사용자종류": null,
		"login": "Hogaeng",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-01-29 11:00:31.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "metatron-app/metatron-discovery"
		],
		"count": 1,
		"사용자종류": null,
		"login": "HoinKim",
		"type": [
		  "WatchEvent"
		],
		"_time": "2019-07-26 02:16:56.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "AlDanial/cloc",
		  "CodeboxIDE/codebox",
		  "Hokwang/p4_jenkins_testenv",
		  "Kong/kong",
		  "PyCQA/pylint",
		  "UniconLabs/java-keystore-ssl-test",
		  "alibaba/Dragonfly",
		  "checkstyle/checkstyle",
		  "codecentric/helm-charts",
		  "codercom/code-server",
		  "coreos/clair",
		  "coreos/prometheus-operator",
		  "cvitter/jenkins-swarm-agent",
		  "danderson/metallb",
		  "danmar/cppcheck",
		  "datawire/ambassador",
		  "debauchee/barrier",
		  "docker/kitematic",
		  "douglascrockford/JSLint",
		  "eclipse/che",
		  "eclipse/orion.client",
		  "elastic/elasticsearch",
		  "elastic/helm-charts",
		  "elastic/kibana",
		  "eldada/jenkins-in-kubernetes",
		  "eldada/jenkins-pipeline-kubernetes",
		  "fffaraz/awesome-cpp",
		  "fomantic/Fomantic-UI",
		  "gamechanger/dusty",
		  "gitpod-io/gitpod",
		  "goharbor/harbor",
		  "goharbor/harbor-helm",
		  "google/blockly",
		  "grafana/grafana",
		  "helm/chartmuseum",
		  "helm/charts",
		  "helm/helm",
		  "hubotio/hubot",
		  "hyperhq/hyperd",
		  "jacoco/jacoco",
		  "jenkins-x/jx",
		  "jenkinsci/blueocean-plugin",
		  "jenkinsci/configuration-as-code-plugin",
		  "jenkinsci/docker",
		  "jenkinsci/docker-swarm-plugin",
		  "jenkinsci/jenkins",
		  "jenkinsci/kubernetes-plugin",
		  "jenkinsci/oic-auth-plugin",
		  "jenkinsci/p4-plugin",
		  "jenkinsci/pipeline-model-definition-plugin",
		  "jetstack/cert-manager",
		  "judexzhu/Jenkins-Pipeline-CI-CD-with-Helm-on-Kubernetes",
		  "kamranahmedse/developer-roadmap",
		  "keycloak/keycloak",
		  "koding/koding",
		  "kubernetes/charts",
		  "kubernetes/dashboard",
		  "kubernetes/heapster",
		  "kubernetes/helm",
		  "kubernetes/ingress-nginx",
		  "kubernetes/kubernetes",
		  "metatron-app/metatron-discovery",
		  "moby/moby",
		  "nextcloud/server",
		  "oleg-nenashev/ci.jenkins.io-runner",
		  "open-policy-agent/opa",
		  "p4paul/p4-jenkins",
		  "pantsbuild/pants",
		  "pmd/pmd",
		  "prometheus/prometheus",
		  "pwm-project/pwm",
		  "rancher/rancher",
		  "roboll/helmfile",
		  "rook/rook",
		  "seanhoughton/p4_exporter",
		  "sourcegraph/sourcegraph",
		  "spinnaker/halyard",
		  "spinnaker/spinnaker",
		  "src-d/engine",
		  "src-d/sourced-ce",
		  "stef-levesque/vscode-perforce",
		  "tektoncd/pipeline",
		  "theia-ide/theia",
		  "uber/kraken",
		  "vmware/harbor"
		],
		"count": 210,
		"사용자종류": null,
		"login": "Hokwang",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-01-13 17:01:20.000+0900"
	  },
	  {
		"meta": 1,
		"repos": [
		  "Hoya-kim/Django-tutorial",
		  "Hoya-kim/Image-Warping-Stitching",
		  "Hoya-kim/Image-warping-stitching",
		  "Hoya-kim/KlasHelper_Android",
		  "Hoya-kim/OpenCV_FormOCR",
		  "Hoya-kim/Random_lottery",
		  "Hoya-kim/Recommend_Recipe_GTA2",
		  "Hoya-kim/Recommend_recipe_front",
		  "Hoya-kim/Vue.js_playgrounds",
		  "Hoya-kim/git_practice_01",
		  "Hoya-kim/git_practice_02",
		  "Hoya-kim/serverless-spa-portfolio",
		  "Hwan-seok/FrontEnd_Study",
		  "Hwan-seok/Javascript_Recent_Gramma",
		  "Hwan-seok/KHU_PON",
		  "Integerous/goQuality-dev-contents",
		  "jh8579/KlasHelper_Android",
		  "kimwj9792/Tibero-Online-Judge",
		  "kushalvyas/Python-Multiple-Image-Stitching",
		  "metatron-app/metatron-discovery"
		],
		"count": 74,
		"사용자종류": null,
		"login": "Hoya-kim",
		"type": [
		  "WatchEvent"
		],
		"_time": "2018-08-15 08:07:18.000+0900"
	  }
	],
	"field_order": [
	  "login",
	  "meta",
	  "count",
	  "type",
	  "_time",
	  "repos"
	],
	"count": 1701
  }